INSERT INTO t_department
   (`departmentId`, `departmentType`, `departmentName`, `departmentIntroduction`, `departmentDirection`, `departmentPlanForOne`, `departmentPlanForTwo`, `departmentPlanForThree`, `departmentPlanForFour`)
VALUES
   (10, 'faxue', '法学专业', '<p>法学专业始建于1986年。20余年来，伴随着中国教育体制的改革与发展，法学专业历经了专科到本科、本科到硕士研究生教育的历程。自1994年开始招收本科生，2002年开始招收经济法学硕士研究生，2010年获得法学硕士一级学科授予权，有经济法学、法理学、宪法与行政法学、民商法学四个研究生专业方向，一个法学本科专业。<br/>法学专业现有专职教师21人，其中教授3人、副教授8人、讲师10人，高职教师占全体教师的比例达到52.4%；博士11人,博士化率达到52.4%，45岁以下教师中具有博士学位（含在读博士）的比例达到72.2%。另外聘兼职法学教授5人，分别担任黑龙江省法学研究所所长副所长、黑龙江省法学会专职副会长、司法职业警官学院院长、中船重工集团常务副总法律顾问等教学研究机构和船舶行业重点企业的主要职务，主要承担研究生指导工作。<br/>法学专业每年高考录取分数均高于黑龙江省重点线20分左右，高考录取分数省内法学专业排名第三，校内文科专业排名第二。法学专业每年招生人数平均在40人左右。现有在校经济法学硕士研究生、法学本科生近250人。已为国家培养硕士研究生近千人，本科生2000余人，专科生500余人，毕业生毕业率100%，就业率近三年平均92.37%以上，考研率近三年平均55.2%，2010年法学本科学生司法考试通过率达到52%。已有相当一部分毕业学生成长为各行业的中坚力量，为我国法制建设和社会发展做出了突出贡献。<br/>法学专业教学科研成果丰硕，现有哈尔滨工程大学校级精品课程2门，获得国家级多媒体课件奖励1项。承担教学研究项目共16项，其中省部级4项。承担科研项目共41项，其中国家社会科学基金、国家软科学课题等国家级项目2项，省部级科研课题21项。近五年科研经费共161.9万元，年均32.38万元，人均8.095万元。发表学术论文共207篇，其中在CSSCI期刊(含扩展版)上发表学术论文70篇，出版学术著作11部。<br/>法学专业积极改善实践教学条件。学校投入建设了高标准模拟法庭实验室，具备实时记录、视频传输、模拟审判、交流互动和地方司法庭审等功能。实验开出率达到100%，仪器设备完好率达到100%，学生参与率达到100%。成立了哈尔滨工程大学法律援助中心；在道外区人民检察院、道外区人民法院等单位建立专业实习基地，在青岛船厂、大连船厂、山海关船厂、葫芦岛船厂等船舶生产企业建立特色实践基地，能够满足实践课程学习的需要，学生的实践能力和创新能力得到明显提升。</p>', '<p>&nbsp;法学专业始建于1986年。20余年来，伴随着中国教育体制的改革与发展，法学专业历经了专科到本科、本科到硕士研究生教育的历程。自1994年开始招收本科生，2002年开始招收经济法学硕士研究生，2010年获得法学硕士一级学科授予权，有经济法学、法理学、宪法与行政法学、民商法学四个研究生专业方向，一个法学本科专业。<br/>法学专业现有专职教师21人，其中教授3人、副教授8人、讲师10人，高职教师占全体教师的比例达到52.4%；博士11人,博士化率达到52.4%，45岁以下教师中具有博士学位（含在读博士）的比例达到72.2%。另外聘兼职法学教授5人，分别担任黑龙江省法学研究所所长副所长、黑龙江省法学会专职副会长、司法职业警官学院院长、中船重工集团常务副总法律顾问等教学研究机构和船舶行业重点企业的主要职务，主要承担研究生指导工作。<br/>法学专业每年高考录取分数均高于黑龙江省重点线20分左右，高考录取分数省内法学专业排名第三，校内文科专业排名第二。法学专业每年招生人数平均在40人左右。现有在校经济法学硕士研究生、法学本科生近250人。已为国家培养硕士研究生近千人，本科生2000余人，专科生500余人，毕业生毕业率100%，就业率近三年平均92.37%以上，考研率近三年平均55.2%，2010年法学本科学生司法考试通过率达到52%。已有相当一部分毕业学生成长为各行业的中坚力量，为我国法制建设和社会发展做出了突出贡献。<br/>法学专业教学科研成果丰硕，现有哈尔滨工程大学校级精品课程2门，获得国家级多媒体课件奖励1项。承担教学研究项目共16项，其中省部级4项。承担科研项目共41项，其中国家社会科学基金、国家软科学课题等国家级项目2项，省部级科研课题21项。近五年科研经费共161.9万元，年均32.38万元，人均8.095万元。发表学术论文共207篇，其中在CSSCI期刊(含扩展版)上发表学术论文70篇，出版学术著作11部。<br/>法学专业积极改善实践教学条件。学校投入建设了高标准模拟法庭实验室，具备实时记录、视频传输、模拟审判、交流互动和地方司法庭审等功能。实验开出率达到100%，仪器设备完好率达到100%，学生参与率达到100%。成立了哈尔滨工程大学法律援助中心；在道外区人民检察院、道外区人民法院等单位建立专业实习基地，在青岛船厂、大连船厂、山海关船厂、葫芦岛船厂等船舶生产企业建立特色实践基地，能够满足实践课程学习的需要，学生的实践能力和创新能力得到明显提升。</p>', , , , );

INSERT INTO t_department
   (`departmentId`, `departmentType`, `departmentName`, `departmentIntroduction`, `departmentDirection`, `departmentPlanForOne`, `departmentPlanForTwo`, `departmentPlanForThree`, `departmentPlanForFour`)
VALUES
   (11, 'faxue', '社会学系', '<p>&nbsp;</p><p><span style=\"font: 13.33px/22.1px 宋体; text-align: left; color: rgb(62, 62, 62); text-indent: 26.66px; letter-spacing: normal; word-spacing: 0px; float: none; display: inline !important; white-space: normal; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;\"><span style=\"color:#000000;font-family:Microsoft YaHei\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>人文社会科学学院应用心理学系自</span><span style=\"font: 13.33px/22.1px 宋体; text-align: left; color: rgb(62, 62, 62); text-indent: 26.66px; letter-spacing: normal; word-spacing: 0px; white-space: normal; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;\">2006</span><span style=\"font: 13.33px/22.1px 宋体; text-align: left; color: rgb(62, 62, 62); text-indent: 26.66px; letter-spacing: normal; word-spacing: 0px; float: none; display: inline !important; white-space: normal; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;\">年成立以来，努力打造符合我校办学方向、服务行业发展需求、有发展前景的特色学科和应用型专业。几年来，我们本着扬长避短、错位竞争与可持续发展策略，突出学科建设重点，凝聚研究合力，加大建设力度，已逐渐形成特色鲜明的学科优势、结构合理的教师队伍及较为完整的心理学人才培养、科学研究、社会服务体系。</span></p>', '<p style=\"font: 13.33px/22.1px 宋体; text-align: left; color: rgb(62, 62, 62); text-indent: 27px; letter-spacing: normal; word-spacing: 0px; white-space: normal; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;\"><span style=\"font-family: 宋体; font-size: 13px;\"></span></p><p style=\"font: 13.33px/22.1px 宋体; text-align: left; color: rgb(62, 62, 62); text-indent: 27px; letter-spacing: normal; word-spacing: 0px; white-space: normal; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;\"><span style=\"font-family: 宋体; font-size: 13px;\">“十二五”期间，我系的主要科研方向定位于“职业心理学”，具体包括职业健康心理学、心理咨询与心理健康教育、思想政治教育心理学三个研究领域。目前，在职业健康心理学研究领域，已经对企业员工的职业倦怠、潜艇艇员的心理压力等进行了探索；在心理咨询与心理健康教育研究领域，对华人应对挫折的生活智慧、心理咨询理论与方法本土化、心理健康教育课程与教学、心理健康教育理论创新等方面，已形成了系列化研究成果；在思想政治教育心理学研究领域，对思想政治教育接受心理、心理教育与道德教育的有效结合等课题进行原创性研究。</span></p><p style=\"font: 13.33px/22.1px 宋体; text-align: left; color: rgb(62, 62, 62); text-indent: 27px; letter-spacing: normal; word-spacing: 0px; white-space: normal; widows: 1; font-size-adjust: none; font-stretch: normal; background-color: rgb(255, 255, 255); -webkit-text-stroke-width: 0px;\"><span style=\"font-family: 宋体; font-size: 13px;\">近几年来，应用心理学系教师已承担国家级、省部级、校级研究课题近<span style=\"undefinedfont-size:12px\">30</span>项，出版著作、教材<span style=\"undefinedfont-size:12px\">20</span>部，发表学术论文<span style=\"undefinedfont-size:12px\">50</span>篇。形成了稳定的研究方向和系列化的研究成果。</span></p><p></p>', , , , );

