package com.et59.cus.domain.entity;

public class TBookclub {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.bookClubId
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private Long bookclubid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.bookClubName
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String bookclubname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.convener
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String convener;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.speaker
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String speaker;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.mainComment
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String maincomment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.comments
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String comments;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.place
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String place;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.time
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String time;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.participants
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String participants;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.subjects
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String subjects;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_bookclub.remark
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.bookClubId
	 * @return  the value of t_bookclub.bookClubId
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public Long getBookclubid() {
		return bookclubid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.bookClubId
	 * @param bookclubid  the value for t_bookclub.bookClubId
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setBookclubid(Long bookclubid) {
		this.bookclubid = bookclubid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.bookClubName
	 * @return  the value of t_bookclub.bookClubName
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getBookclubname() {
		return bookclubname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.bookClubName
	 * @param bookclubname  the value for t_bookclub.bookClubName
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setBookclubname(String bookclubname) {
		this.bookclubname = bookclubname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.convener
	 * @return  the value of t_bookclub.convener
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getConvener() {
		return convener;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.convener
	 * @param convener  the value for t_bookclub.convener
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setConvener(String convener) {
		this.convener = convener;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.speaker
	 * @return  the value of t_bookclub.speaker
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getSpeaker() {
		return speaker;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.speaker
	 * @param speaker  the value for t_bookclub.speaker
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setSpeaker(String speaker) {
		this.speaker = speaker;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.mainComment
	 * @return  the value of t_bookclub.mainComment
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getMaincomment() {
		return maincomment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.mainComment
	 * @param maincomment  the value for t_bookclub.mainComment
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setMaincomment(String maincomment) {
		this.maincomment = maincomment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.comments
	 * @return  the value of t_bookclub.comments
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.comments
	 * @param comments  the value for t_bookclub.comments
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.place
	 * @return  the value of t_bookclub.place
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getPlace() {
		return place;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.place
	 * @param place  the value for t_bookclub.place
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setPlace(String place) {
		this.place = place;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.time
	 * @return  the value of t_bookclub.time
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.time
	 * @param time  the value for t_bookclub.time
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.participants
	 * @return  the value of t_bookclub.participants
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getParticipants() {
		return participants;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.participants
	 * @param participants  the value for t_bookclub.participants
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setParticipants(String participants) {
		this.participants = participants;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.subjects
	 * @return  the value of t_bookclub.subjects
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getSubjects() {
		return subjects;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.subjects
	 * @param subjects  the value for t_bookclub.subjects
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setSubjects(String subjects) {
		this.subjects = subjects;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_bookclub.remark
	 * @return  the value of t_bookclub.remark
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_bookclub.remark
	 * @param remark  the value for t_bookclub.remark
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}