package com.et59.cus.domain.entity;

import java.util.Date;

public class TDownload {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.id
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.filename
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private String filename;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.filepath
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private String filepath;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.fileisvalid
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private String fileisvalid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.createdate
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private Date createdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.author
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private String author;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.directions
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private String directions;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.infotype
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private Integer infotype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_download.infoorder
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	private Integer infoorder;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.id
	 * @return  the value of t_download.id
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.id
	 * @param id  the value for t_download.id
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.filename
	 * @return  the value of t_download.filename
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.filename
	 * @param filename  the value for t_download.filename
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.filepath
	 * @return  the value of t_download.filepath
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public String getFilepath() {
		return filepath;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.filepath
	 * @param filepath  the value for t_download.filepath
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.fileisvalid
	 * @return  the value of t_download.fileisvalid
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public String getFileisvalid() {
		return fileisvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.fileisvalid
	 * @param fileisvalid  the value for t_download.fileisvalid
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setFileisvalid(String fileisvalid) {
		this.fileisvalid = fileisvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.createdate
	 * @return  the value of t_download.createdate
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.createdate
	 * @param createdate  the value for t_download.createdate
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.author
	 * @return  the value of t_download.author
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.author
	 * @param author  the value for t_download.author
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.directions
	 * @return  the value of t_download.directions
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public String getDirections() {
		return directions;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.directions
	 * @param directions  the value for t_download.directions
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setDirections(String directions) {
		this.directions = directions;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.infotype
	 * @return  the value of t_download.infotype
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public Integer getInfotype() {
		return infotype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.infotype
	 * @param infotype  the value for t_download.infotype
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setInfotype(Integer infotype) {
		this.infotype = infotype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_download.infoorder
	 * @return  the value of t_download.infoorder
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public Integer getInfoorder() {
		return infoorder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_download.infoorder
	 * @param infoorder  the value for t_download.infoorder
	 * @ibatorgenerated  Mon Dec 29 11:22:13 CST 2014
	 */
	public void setInfoorder(Integer infoorder) {
		this.infoorder = infoorder;
	}

}