package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TExchangeStuExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public TExchangeStuExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	protected TExchangeStuExample(TExchangeStuExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_exchange_stu
	 * @ibatorgenerated  Wed Aug 26 16:25:05 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andExchangestuidIsNull() {
			addCriterion("exchangeStuId is null");
			return this;
		}

		public Criteria andExchangestuidIsNotNull() {
			addCriterion("exchangeStuId is not null");
			return this;
		}

		public Criteria andExchangestuidEqualTo(Long value) {
			addCriterion("exchangeStuId =", value, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidNotEqualTo(Long value) {
			addCriterion("exchangeStuId <>", value, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidGreaterThan(Long value) {
			addCriterion("exchangeStuId >", value, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidGreaterThanOrEqualTo(Long value) {
			addCriterion("exchangeStuId >=", value, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidLessThan(Long value) {
			addCriterion("exchangeStuId <", value, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidLessThanOrEqualTo(Long value) {
			addCriterion("exchangeStuId <=", value, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidIn(List values) {
			addCriterion("exchangeStuId in", values, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidNotIn(List values) {
			addCriterion("exchangeStuId not in", values, "exchangestuid");
			return this;
		}

		public Criteria andExchangestuidBetween(Long value1, Long value2) {
			addCriterion("exchangeStuId between", value1, value2,
					"exchangestuid");
			return this;
		}

		public Criteria andExchangestuidNotBetween(Long value1, Long value2) {
			addCriterion("exchangeStuId not between", value1, value2,
					"exchangestuid");
			return this;
		}

		public Criteria andStunameIsNull() {
			addCriterion("stuName is null");
			return this;
		}

		public Criteria andStunameIsNotNull() {
			addCriterion("stuName is not null");
			return this;
		}

		public Criteria andStunameEqualTo(String value) {
			addCriterion("stuName =", value, "stuname");
			return this;
		}

		public Criteria andStunameNotEqualTo(String value) {
			addCriterion("stuName <>", value, "stuname");
			return this;
		}

		public Criteria andStunameGreaterThan(String value) {
			addCriterion("stuName >", value, "stuname");
			return this;
		}

		public Criteria andStunameGreaterThanOrEqualTo(String value) {
			addCriterion("stuName >=", value, "stuname");
			return this;
		}

		public Criteria andStunameLessThan(String value) {
			addCriterion("stuName <", value, "stuname");
			return this;
		}

		public Criteria andStunameLessThanOrEqualTo(String value) {
			addCriterion("stuName <=", value, "stuname");
			return this;
		}

		public Criteria andStunameLike(String value) {
			addCriterion("stuName like", value, "stuname");
			return this;
		}

		public Criteria andStunameNotLike(String value) {
			addCriterion("stuName not like", value, "stuname");
			return this;
		}

		public Criteria andStunameIn(List values) {
			addCriterion("stuName in", values, "stuname");
			return this;
		}

		public Criteria andStunameNotIn(List values) {
			addCriterion("stuName not in", values, "stuname");
			return this;
		}

		public Criteria andStunameBetween(String value1, String value2) {
			addCriterion("stuName between", value1, value2, "stuname");
			return this;
		}

		public Criteria andStunameNotBetween(String value1, String value2) {
			addCriterion("stuName not between", value1, value2, "stuname");
			return this;
		}

		public Criteria andStutypeIsNull() {
			addCriterion("stuType is null");
			return this;
		}

		public Criteria andStutypeIsNotNull() {
			addCriterion("stuType is not null");
			return this;
		}

		public Criteria andStutypeEqualTo(String value) {
			addCriterion("stuType =", value, "stutype");
			return this;
		}

		public Criteria andStutypeNotEqualTo(String value) {
			addCriterion("stuType <>", value, "stutype");
			return this;
		}

		public Criteria andStutypeGreaterThan(String value) {
			addCriterion("stuType >", value, "stutype");
			return this;
		}

		public Criteria andStutypeGreaterThanOrEqualTo(String value) {
			addCriterion("stuType >=", value, "stutype");
			return this;
		}

		public Criteria andStutypeLessThan(String value) {
			addCriterion("stuType <", value, "stutype");
			return this;
		}

		public Criteria andStutypeLessThanOrEqualTo(String value) {
			addCriterion("stuType <=", value, "stutype");
			return this;
		}

		public Criteria andStutypeLike(String value) {
			addCriterion("stuType like", value, "stutype");
			return this;
		}

		public Criteria andStutypeNotLike(String value) {
			addCriterion("stuType not like", value, "stutype");
			return this;
		}

		public Criteria andStutypeIn(List values) {
			addCriterion("stuType in", values, "stutype");
			return this;
		}

		public Criteria andStutypeNotIn(List values) {
			addCriterion("stuType not in", values, "stutype");
			return this;
		}

		public Criteria andStutypeBetween(String value1, String value2) {
			addCriterion("stuType between", value1, value2, "stutype");
			return this;
		}

		public Criteria andStutypeNotBetween(String value1, String value2) {
			addCriterion("stuType not between", value1, value2, "stutype");
			return this;
		}

		public Criteria andExchangebegintimeIsNull() {
			addCriterion("exchangeBeginTime is null");
			return this;
		}

		public Criteria andExchangebegintimeIsNotNull() {
			addCriterion("exchangeBeginTime is not null");
			return this;
		}

		public Criteria andExchangebegintimeEqualTo(String value) {
			addCriterion("exchangeBeginTime =", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeNotEqualTo(String value) {
			addCriterion("exchangeBeginTime <>", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeGreaterThan(String value) {
			addCriterion("exchangeBeginTime >", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeGreaterThanOrEqualTo(String value) {
			addCriterion("exchangeBeginTime >=", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeLessThan(String value) {
			addCriterion("exchangeBeginTime <", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeLessThanOrEqualTo(String value) {
			addCriterion("exchangeBeginTime <=", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeLike(String value) {
			addCriterion("exchangeBeginTime like", value, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeNotLike(String value) {
			addCriterion("exchangeBeginTime not like", value,
					"exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeIn(List values) {
			addCriterion("exchangeBeginTime in", values, "exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeNotIn(List values) {
			addCriterion("exchangeBeginTime not in", values,
					"exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeBetween(String value1, String value2) {
			addCriterion("exchangeBeginTime between", value1, value2,
					"exchangebegintime");
			return this;
		}

		public Criteria andExchangebegintimeNotBetween(String value1,
				String value2) {
			addCriterion("exchangeBeginTime not between", value1, value2,
					"exchangebegintime");
			return this;
		}

		public Criteria andExchangeendtimeIsNull() {
			addCriterion("exchangeEndTime is null");
			return this;
		}

		public Criteria andExchangeendtimeIsNotNull() {
			addCriterion("exchangeEndTime is not null");
			return this;
		}

		public Criteria andExchangeendtimeEqualTo(String value) {
			addCriterion("exchangeEndTime =", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeNotEqualTo(String value) {
			addCriterion("exchangeEndTime <>", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeGreaterThan(String value) {
			addCriterion("exchangeEndTime >", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeGreaterThanOrEqualTo(String value) {
			addCriterion("exchangeEndTime >=", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeLessThan(String value) {
			addCriterion("exchangeEndTime <", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeLessThanOrEqualTo(String value) {
			addCriterion("exchangeEndTime <=", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeLike(String value) {
			addCriterion("exchangeEndTime like", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeNotLike(String value) {
			addCriterion("exchangeEndTime not like", value, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeIn(List values) {
			addCriterion("exchangeEndTime in", values, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeNotIn(List values) {
			addCriterion("exchangeEndTime not in", values, "exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeBetween(String value1, String value2) {
			addCriterion("exchangeEndTime between", value1, value2,
					"exchangeendtime");
			return this;
		}

		public Criteria andExchangeendtimeNotBetween(String value1,
				String value2) {
			addCriterion("exchangeEndTime not between", value1, value2,
					"exchangeendtime");
			return this;
		}

		public Criteria andTimelengthIsNull() {
			addCriterion("timeLength is null");
			return this;
		}

		public Criteria andTimelengthIsNotNull() {
			addCriterion("timeLength is not null");
			return this;
		}

		public Criteria andTimelengthEqualTo(String value) {
			addCriterion("timeLength =", value, "timelength");
			return this;
		}

		public Criteria andTimelengthNotEqualTo(String value) {
			addCriterion("timeLength <>", value, "timelength");
			return this;
		}

		public Criteria andTimelengthGreaterThan(String value) {
			addCriterion("timeLength >", value, "timelength");
			return this;
		}

		public Criteria andTimelengthGreaterThanOrEqualTo(String value) {
			addCriterion("timeLength >=", value, "timelength");
			return this;
		}

		public Criteria andTimelengthLessThan(String value) {
			addCriterion("timeLength <", value, "timelength");
			return this;
		}

		public Criteria andTimelengthLessThanOrEqualTo(String value) {
			addCriterion("timeLength <=", value, "timelength");
			return this;
		}

		public Criteria andTimelengthLike(String value) {
			addCriterion("timeLength like", value, "timelength");
			return this;
		}

		public Criteria andTimelengthNotLike(String value) {
			addCriterion("timeLength not like", value, "timelength");
			return this;
		}

		public Criteria andTimelengthIn(List values) {
			addCriterion("timeLength in", values, "timelength");
			return this;
		}

		public Criteria andTimelengthNotIn(List values) {
			addCriterion("timeLength not in", values, "timelength");
			return this;
		}

		public Criteria andTimelengthBetween(String value1, String value2) {
			addCriterion("timeLength between", value1, value2, "timelength");
			return this;
		}

		public Criteria andTimelengthNotBetween(String value1, String value2) {
			addCriterion("timeLength not between", value1, value2, "timelength");
			return this;
		}

		public Criteria andExchangeplaceIsNull() {
			addCriterion("exchangePlace is null");
			return this;
		}

		public Criteria andExchangeplaceIsNotNull() {
			addCriterion("exchangePlace is not null");
			return this;
		}

		public Criteria andExchangeplaceEqualTo(String value) {
			addCriterion("exchangePlace =", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceNotEqualTo(String value) {
			addCriterion("exchangePlace <>", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceGreaterThan(String value) {
			addCriterion("exchangePlace >", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceGreaterThanOrEqualTo(String value) {
			addCriterion("exchangePlace >=", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceLessThan(String value) {
			addCriterion("exchangePlace <", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceLessThanOrEqualTo(String value) {
			addCriterion("exchangePlace <=", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceLike(String value) {
			addCriterion("exchangePlace like", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceNotLike(String value) {
			addCriterion("exchangePlace not like", value, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceIn(List values) {
			addCriterion("exchangePlace in", values, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceNotIn(List values) {
			addCriterion("exchangePlace not in", values, "exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceBetween(String value1, String value2) {
			addCriterion("exchangePlace between", value1, value2,
					"exchangeplace");
			return this;
		}

		public Criteria andExchangeplaceNotBetween(String value1, String value2) {
			addCriterion("exchangePlace not between", value1, value2,
					"exchangeplace");
			return this;
		}

		public Criteria andProjectnameIsNull() {
			addCriterion("projectName is null");
			return this;
		}

		public Criteria andProjectnameIsNotNull() {
			addCriterion("projectName is not null");
			return this;
		}

		public Criteria andProjectnameEqualTo(String value) {
			addCriterion("projectName =", value, "projectname");
			return this;
		}

		public Criteria andProjectnameNotEqualTo(String value) {
			addCriterion("projectName <>", value, "projectname");
			return this;
		}

		public Criteria andProjectnameGreaterThan(String value) {
			addCriterion("projectName >", value, "projectname");
			return this;
		}

		public Criteria andProjectnameGreaterThanOrEqualTo(String value) {
			addCriterion("projectName >=", value, "projectname");
			return this;
		}

		public Criteria andProjectnameLessThan(String value) {
			addCriterion("projectName <", value, "projectname");
			return this;
		}

		public Criteria andProjectnameLessThanOrEqualTo(String value) {
			addCriterion("projectName <=", value, "projectname");
			return this;
		}

		public Criteria andProjectnameLike(String value) {
			addCriterion("projectName like", value, "projectname");
			return this;
		}

		public Criteria andProjectnameNotLike(String value) {
			addCriterion("projectName not like", value, "projectname");
			return this;
		}

		public Criteria andProjectnameIn(List values) {
			addCriterion("projectName in", values, "projectname");
			return this;
		}

		public Criteria andProjectnameNotIn(List values) {
			addCriterion("projectName not in", values, "projectname");
			return this;
		}

		public Criteria andProjectnameBetween(String value1, String value2) {
			addCriterion("projectName between", value1, value2, "projectname");
			return this;
		}

		public Criteria andProjectnameNotBetween(String value1, String value2) {
			addCriterion("projectName not between", value1, value2,
					"projectname");
			return this;
		}
	}
}