package com.et59.cus.domain.entity;

public class TExchangeStu {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.exchangeStuId
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private Long exchangestuid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.stuName
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String stuname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.stuType
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String stutype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.exchangeBeginTime
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String exchangebegintime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.exchangeEndTime
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String exchangeendtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.timeLength
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String timelength;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.exchangePlace
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String exchangeplace;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_exchange_stu.projectName
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private String projectname;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.exchangeStuId
     *
     * @return the value of t_exchange_stu.exchangeStuId
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public Long getExchangestuid() {
        return exchangestuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.exchangeStuId
     *
     * @param exchangestuid the value for t_exchange_stu.exchangeStuId
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setExchangestuid(Long exchangestuid) {
        this.exchangestuid = exchangestuid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.stuName
     *
     * @return the value of t_exchange_stu.stuName
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.stuName
     *
     * @param stuname the value for t_exchange_stu.stuName
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setStuname(String stuname) {
        this.stuname = stuname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.stuType
     *
     * @return the value of t_exchange_stu.stuType
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getStutype() {
        return stutype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.stuType
     *
     * @param stutype the value for t_exchange_stu.stuType
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setStutype(String stutype) {
        this.stutype = stutype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.exchangeBeginTime
     *
     * @return the value of t_exchange_stu.exchangeBeginTime
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getExchangebegintime() {
        return exchangebegintime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.exchangeBeginTime
     *
     * @param exchangebegintime the value for t_exchange_stu.exchangeBeginTime
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setExchangebegintime(String exchangebegintime) {
        this.exchangebegintime = exchangebegintime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.exchangeEndTime
     *
     * @return the value of t_exchange_stu.exchangeEndTime
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getExchangeendtime() {
        return exchangeendtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.exchangeEndTime
     *
     * @param exchangeendtime the value for t_exchange_stu.exchangeEndTime
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setExchangeendtime(String exchangeendtime) {
        this.exchangeendtime = exchangeendtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.timeLength
     *
     * @return the value of t_exchange_stu.timeLength
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getTimelength() {
        return timelength;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.timeLength
     *
     * @param timelength the value for t_exchange_stu.timeLength
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setTimelength(String timelength) {
        this.timelength = timelength;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.exchangePlace
     *
     * @return the value of t_exchange_stu.exchangePlace
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getExchangeplace() {
        return exchangeplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.exchangePlace
     *
     * @param exchangeplace the value for t_exchange_stu.exchangePlace
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setExchangeplace(String exchangeplace) {
        this.exchangeplace = exchangeplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_exchange_stu.projectName
     *
     * @return the value of t_exchange_stu.projectName
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_exchange_stu.projectName
     *
     * @param projectname the value for t_exchange_stu.projectName
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }
}