package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TForeignExpertsExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public TForeignExpertsExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    protected TForeignExpertsExample(TForeignExpertsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andForeignidIsNull() {
            addCriterion("foreignId is null");
            return this;
        }

        public Criteria andForeignidIsNotNull() {
            addCriterion("foreignId is not null");
            return this;
        }

        public Criteria andForeignidEqualTo(Long value) {
            addCriterion("foreignId =", value, "foreignid");
            return this;
        }

        public Criteria andForeignidNotEqualTo(Long value) {
            addCriterion("foreignId <>", value, "foreignid");
            return this;
        }

        public Criteria andForeignidGreaterThan(Long value) {
            addCriterion("foreignId >", value, "foreignid");
            return this;
        }

        public Criteria andForeignidGreaterThanOrEqualTo(Long value) {
            addCriterion("foreignId >=", value, "foreignid");
            return this;
        }

        public Criteria andForeignidLessThan(Long value) {
            addCriterion("foreignId <", value, "foreignid");
            return this;
        }

        public Criteria andForeignidLessThanOrEqualTo(Long value) {
            addCriterion("foreignId <=", value, "foreignid");
            return this;
        }

        public Criteria andForeignidIn(List values) {
            addCriterion("foreignId in", values, "foreignid");
            return this;
        }

        public Criteria andForeignidNotIn(List values) {
            addCriterion("foreignId not in", values, "foreignid");
            return this;
        }

        public Criteria andForeignidBetween(Long value1, Long value2) {
            addCriterion("foreignId between", value1, value2, "foreignid");
            return this;
        }

        public Criteria andForeignidNotBetween(Long value1, Long value2) {
            addCriterion("foreignId not between", value1, value2, "foreignid");
            return this;
        }

        public Criteria andFprojectmanagerIsNull() {
            addCriterion("fprojectmanager is null");
            return this;
        }

        public Criteria andFprojectmanagerIsNotNull() {
            addCriterion("fprojectmanager is not null");
            return this;
        }

        public Criteria andFprojectmanagerEqualTo(String value) {
            addCriterion("fprojectmanager =", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerNotEqualTo(String value) {
            addCriterion("fprojectmanager <>", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerGreaterThan(String value) {
            addCriterion("fprojectmanager >", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerGreaterThanOrEqualTo(String value) {
            addCriterion("fprojectmanager >=", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerLessThan(String value) {
            addCriterion("fprojectmanager <", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerLessThanOrEqualTo(String value) {
            addCriterion("fprojectmanager <=", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerLike(String value) {
            addCriterion("fprojectmanager like", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerNotLike(String value) {
            addCriterion("fprojectmanager not like", value, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerIn(List values) {
            addCriterion("fprojectmanager in", values, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerNotIn(List values) {
            addCriterion("fprojectmanager not in", values, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerBetween(String value1, String value2) {
            addCriterion("fprojectmanager between", value1, value2, "fprojectmanager");
            return this;
        }

        public Criteria andFprojectmanagerNotBetween(String value1, String value2) {
            addCriterion("fprojectmanager not between", value1, value2, "fprojectmanager");
            return this;
        }

        public Criteria andFprojecttypeIsNull() {
            addCriterion("fprojectType is null");
            return this;
        }

        public Criteria andFprojecttypeIsNotNull() {
            addCriterion("fprojectType is not null");
            return this;
        }

        public Criteria andFprojecttypeEqualTo(String value) {
            addCriterion("fprojectType =", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeNotEqualTo(String value) {
            addCriterion("fprojectType <>", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeGreaterThan(String value) {
            addCriterion("fprojectType >", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeGreaterThanOrEqualTo(String value) {
            addCriterion("fprojectType >=", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeLessThan(String value) {
            addCriterion("fprojectType <", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeLessThanOrEqualTo(String value) {
            addCriterion("fprojectType <=", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeLike(String value) {
            addCriterion("fprojectType like", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeNotLike(String value) {
            addCriterion("fprojectType not like", value, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeIn(List values) {
            addCriterion("fprojectType in", values, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeNotIn(List values) {
            addCriterion("fprojectType not in", values, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeBetween(String value1, String value2) {
            addCriterion("fprojectType between", value1, value2, "fprojecttype");
            return this;
        }

        public Criteria andFprojecttypeNotBetween(String value1, String value2) {
            addCriterion("fprojectType not between", value1, value2, "fprojecttype");
            return this;
        }

        public Criteria andExpertnameIsNull() {
            addCriterion("expertName is null");
            return this;
        }

        public Criteria andExpertnameIsNotNull() {
            addCriterion("expertName is not null");
            return this;
        }

        public Criteria andExpertnameEqualTo(String value) {
            addCriterion("expertName =", value, "expertname");
            return this;
        }

        public Criteria andExpertnameNotEqualTo(String value) {
            addCriterion("expertName <>", value, "expertname");
            return this;
        }

        public Criteria andExpertnameGreaterThan(String value) {
            addCriterion("expertName >", value, "expertname");
            return this;
        }

        public Criteria andExpertnameGreaterThanOrEqualTo(String value) {
            addCriterion("expertName >=", value, "expertname");
            return this;
        }

        public Criteria andExpertnameLessThan(String value) {
            addCriterion("expertName <", value, "expertname");
            return this;
        }

        public Criteria andExpertnameLessThanOrEqualTo(String value) {
            addCriterion("expertName <=", value, "expertname");
            return this;
        }

        public Criteria andExpertnameLike(String value) {
            addCriterion("expertName like", value, "expertname");
            return this;
        }

        public Criteria andExpertnameNotLike(String value) {
            addCriterion("expertName not like", value, "expertname");
            return this;
        }

        public Criteria andExpertnameIn(List values) {
            addCriterion("expertName in", values, "expertname");
            return this;
        }

        public Criteria andExpertnameNotIn(List values) {
            addCriterion("expertName not in", values, "expertname");
            return this;
        }

        public Criteria andExpertnameBetween(String value1, String value2) {
            addCriterion("expertName between", value1, value2, "expertname");
            return this;
        }

        public Criteria andExpertnameNotBetween(String value1, String value2) {
            addCriterion("expertName not between", value1, value2, "expertname");
            return this;
        }

        public Criteria andExpertnationalityIsNull() {
            addCriterion("expertNationality is null");
            return this;
        }

        public Criteria andExpertnationalityIsNotNull() {
            addCriterion("expertNationality is not null");
            return this;
        }

        public Criteria andExpertnationalityEqualTo(String value) {
            addCriterion("expertNationality =", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityNotEqualTo(String value) {
            addCriterion("expertNationality <>", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityGreaterThan(String value) {
            addCriterion("expertNationality >", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityGreaterThanOrEqualTo(String value) {
            addCriterion("expertNationality >=", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityLessThan(String value) {
            addCriterion("expertNationality <", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityLessThanOrEqualTo(String value) {
            addCriterion("expertNationality <=", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityLike(String value) {
            addCriterion("expertNationality like", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityNotLike(String value) {
            addCriterion("expertNationality not like", value, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityIn(List values) {
            addCriterion("expertNationality in", values, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityNotIn(List values) {
            addCriterion("expertNationality not in", values, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityBetween(String value1, String value2) {
            addCriterion("expertNationality between", value1, value2, "expertnationality");
            return this;
        }

        public Criteria andExpertnationalityNotBetween(String value1, String value2) {
            addCriterion("expertNationality not between", value1, value2, "expertnationality");
            return this;
        }

        public Criteria andWorkunitIsNull() {
            addCriterion("workUnit is null");
            return this;
        }

        public Criteria andWorkunitIsNotNull() {
            addCriterion("workUnit is not null");
            return this;
        }

        public Criteria andWorkunitEqualTo(String value) {
            addCriterion("workUnit =", value, "workunit");
            return this;
        }

        public Criteria andWorkunitNotEqualTo(String value) {
            addCriterion("workUnit <>", value, "workunit");
            return this;
        }

        public Criteria andWorkunitGreaterThan(String value) {
            addCriterion("workUnit >", value, "workunit");
            return this;
        }

        public Criteria andWorkunitGreaterThanOrEqualTo(String value) {
            addCriterion("workUnit >=", value, "workunit");
            return this;
        }

        public Criteria andWorkunitLessThan(String value) {
            addCriterion("workUnit <", value, "workunit");
            return this;
        }

        public Criteria andWorkunitLessThanOrEqualTo(String value) {
            addCriterion("workUnit <=", value, "workunit");
            return this;
        }

        public Criteria andWorkunitLike(String value) {
            addCriterion("workUnit like", value, "workunit");
            return this;
        }

        public Criteria andWorkunitNotLike(String value) {
            addCriterion("workUnit not like", value, "workunit");
            return this;
        }

        public Criteria andWorkunitIn(List values) {
            addCriterion("workUnit in", values, "workunit");
            return this;
        }

        public Criteria andWorkunitNotIn(List values) {
            addCriterion("workUnit not in", values, "workunit");
            return this;
        }

        public Criteria andWorkunitBetween(String value1, String value2) {
            addCriterion("workUnit between", value1, value2, "workunit");
            return this;
        }

        public Criteria andWorkunitNotBetween(String value1, String value2) {
            addCriterion("workUnit not between", value1, value2, "workunit");
            return this;
        }

        public Criteria andVisittimeIsNull() {
            addCriterion("visitTime is null");
            return this;
        }

        public Criteria andVisittimeIsNotNull() {
            addCriterion("visitTime is not null");
            return this;
        }

        public Criteria andVisittimeEqualTo(String value) {
            addCriterion("visitTime =", value, "visittime");
            return this;
        }

        public Criteria andVisittimeNotEqualTo(String value) {
            addCriterion("visitTime <>", value, "visittime");
            return this;
        }

        public Criteria andVisittimeGreaterThan(String value) {
            addCriterion("visitTime >", value, "visittime");
            return this;
        }

        public Criteria andVisittimeGreaterThanOrEqualTo(String value) {
            addCriterion("visitTime >=", value, "visittime");
            return this;
        }

        public Criteria andVisittimeLessThan(String value) {
            addCriterion("visitTime <", value, "visittime");
            return this;
        }

        public Criteria andVisittimeLessThanOrEqualTo(String value) {
            addCriterion("visitTime <=", value, "visittime");
            return this;
        }

        public Criteria andVisittimeLike(String value) {
            addCriterion("visitTime like", value, "visittime");
            return this;
        }

        public Criteria andVisittimeNotLike(String value) {
            addCriterion("visitTime not like", value, "visittime");
            return this;
        }

        public Criteria andVisittimeIn(List values) {
            addCriterion("visitTime in", values, "visittime");
            return this;
        }

        public Criteria andVisittimeNotIn(List values) {
            addCriterion("visitTime not in", values, "visittime");
            return this;
        }

        public Criteria andVisittimeBetween(String value1, String value2) {
            addCriterion("visitTime between", value1, value2, "visittime");
            return this;
        }

        public Criteria andVisittimeNotBetween(String value1, String value2) {
            addCriterion("visitTime not between", value1, value2, "visittime");
            return this;
        }

        public Criteria andVisitgoalIsNull() {
            addCriterion("visitGoal is null");
            return this;
        }

        public Criteria andVisitgoalIsNotNull() {
            addCriterion("visitGoal is not null");
            return this;
        }

        public Criteria andVisitgoalEqualTo(String value) {
            addCriterion("visitGoal =", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalNotEqualTo(String value) {
            addCriterion("visitGoal <>", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalGreaterThan(String value) {
            addCriterion("visitGoal >", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalGreaterThanOrEqualTo(String value) {
            addCriterion("visitGoal >=", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalLessThan(String value) {
            addCriterion("visitGoal <", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalLessThanOrEqualTo(String value) {
            addCriterion("visitGoal <=", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalLike(String value) {
            addCriterion("visitGoal like", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalNotLike(String value) {
            addCriterion("visitGoal not like", value, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalIn(List values) {
            addCriterion("visitGoal in", values, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalNotIn(List values) {
            addCriterion("visitGoal not in", values, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalBetween(String value1, String value2) {
            addCriterion("visitGoal between", value1, value2, "visitgoal");
            return this;
        }

        public Criteria andVisitgoalNotBetween(String value1, String value2) {
            addCriterion("visitGoal not between", value1, value2, "visitgoal");
            return this;
        }

        public Criteria andVisitactivityIsNull() {
            addCriterion("visitActivity is null");
            return this;
        }

        public Criteria andVisitactivityIsNotNull() {
            addCriterion("visitActivity is not null");
            return this;
        }

        public Criteria andVisitactivityEqualTo(String value) {
            addCriterion("visitActivity =", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityNotEqualTo(String value) {
            addCriterion("visitActivity <>", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityGreaterThan(String value) {
            addCriterion("visitActivity >", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityGreaterThanOrEqualTo(String value) {
            addCriterion("visitActivity >=", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityLessThan(String value) {
            addCriterion("visitActivity <", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityLessThanOrEqualTo(String value) {
            addCriterion("visitActivity <=", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityLike(String value) {
            addCriterion("visitActivity like", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityNotLike(String value) {
            addCriterion("visitActivity not like", value, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityIn(List values) {
            addCriterion("visitActivity in", values, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityNotIn(List values) {
            addCriterion("visitActivity not in", values, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityBetween(String value1, String value2) {
            addCriterion("visitActivity between", value1, value2, "visitactivity");
            return this;
        }

        public Criteria andVisitactivityNotBetween(String value1, String value2) {
            addCriterion("visitActivity not between", value1, value2, "visitactivity");
            return this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("other is null");
            return this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("other is not null");
            return this;
        }

        public Criteria andOtherEqualTo(String value) {
            addCriterion("other =", value, "other");
            return this;
        }

        public Criteria andOtherNotEqualTo(String value) {
            addCriterion("other <>", value, "other");
            return this;
        }

        public Criteria andOtherGreaterThan(String value) {
            addCriterion("other >", value, "other");
            return this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(String value) {
            addCriterion("other >=", value, "other");
            return this;
        }

        public Criteria andOtherLessThan(String value) {
            addCriterion("other <", value, "other");
            return this;
        }

        public Criteria andOtherLessThanOrEqualTo(String value) {
            addCriterion("other <=", value, "other");
            return this;
        }

        public Criteria andOtherLike(String value) {
            addCriterion("other like", value, "other");
            return this;
        }

        public Criteria andOtherNotLike(String value) {
            addCriterion("other not like", value, "other");
            return this;
        }

        public Criteria andOtherIn(List values) {
            addCriterion("other in", values, "other");
            return this;
        }

        public Criteria andOtherNotIn(List values) {
            addCriterion("other not in", values, "other");
            return this;
        }

        public Criteria andOtherBetween(String value1, String value2) {
            addCriterion("other between", value1, value2, "other");
            return this;
        }

        public Criteria andOtherNotBetween(String value1, String value2) {
            addCriterion("other not between", value1, value2, "other");
            return this;
        }
    }
}