package com.et59.cus.domain.entity;

public class THonoraward {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.honorAwardId
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private Long honorawardid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.teamMember
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String teammember;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.honorType
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String honortype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.grantOrg
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String grantorg;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.grantTime
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String granttime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.teacherNames
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String teachernames;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.remark
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_honoraward.honorName
	 * 
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	private String honorname;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.honorAwardId
	 * 
	 * @return the value of t_honoraward.honorAwardId
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public Long getHonorawardid() {
		return honorawardid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.honorAwardId
	 * 
	 * @param honorawardid
	 *            the value for t_honoraward.honorAwardId
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setHonorawardid(Long honorawardid) {
		this.honorawardid = honorawardid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.teamMember
	 * 
	 * @return the value of t_honoraward.teamMember
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getTeammember() {
		return teammember;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.teamMember
	 * 
	 * @param teammember
	 *            the value for t_honoraward.teamMember
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setTeammember(String teammember) {
		this.teammember = teammember;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.honorType
	 * 
	 * @return the value of t_honoraward.honorType
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getHonortype() {
		return honortype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.honorType
	 * 
	 * @param honortype
	 *            the value for t_honoraward.honorType
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setHonortype(String honortype) {
		this.honortype = honortype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.grantOrg
	 * 
	 * @return the value of t_honoraward.grantOrg
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getGrantorg() {
		return grantorg;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.grantOrg
	 * 
	 * @param grantorg
	 *            the value for t_honoraward.grantOrg
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setGrantorg(String grantorg) {
		this.grantorg = grantorg;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.grantTime
	 * 
	 * @return the value of t_honoraward.grantTime
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getGranttime() {
		return granttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.grantTime
	 * 
	 * @param granttime
	 *            the value for t_honoraward.grantTime
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setGranttime(String granttime) {
		this.granttime = granttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.teacherNames
	 * 
	 * @return the value of t_honoraward.teacherNames
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getTeachernames() {
		return teachernames;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.teacherNames
	 * 
	 * @param teachernames
	 *            the value for t_honoraward.teacherNames
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setTeachernames(String teachernames) {
		this.teachernames = teachernames;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.remark
	 * 
	 * @return the value of t_honoraward.remark
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.remark
	 * 
	 * @param remark
	 *            the value for t_honoraward.remark
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_honoraward.honorName
	 * 
	 * @return the value of t_honoraward.honorName
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public String getHonorname() {
		return honorname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_honoraward.honorName
	 * 
	 * @param honorname
	 *            the value for t_honoraward.honorName
	 * @ibatorgenerated Tue Jul 21 14:34:35 CST 2015
	 */
	public void setHonorname(String honorname) {
		this.honorname = honorname;
	}

}