package com.et59.cus.domain.entity;

public class TLearnact {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.actId
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private Long actid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.actName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String actname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.expertNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String expertnames;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.teacherNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String teachernames;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.studentNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String studentnames;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.actPlace
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String actplace;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.actTime
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String acttime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.subjects
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String subjects;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_learnact.remark
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String remark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.actId
     *
     * @return the value of t_learnact.actId
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public Long getActid() {
        return actid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.actId
     *
     * @param actid the value for t_learnact.actId
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setActid(Long actid) {
        this.actid = actid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.actName
     *
     * @return the value of t_learnact.actName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getActname() {
        return actname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.actName
     *
     * @param actname the value for t_learnact.actName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setActname(String actname) {
        this.actname = actname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.expertNames
     *
     * @return the value of t_learnact.expertNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getExpertnames() {
        return expertnames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.expertNames
     *
     * @param expertnames the value for t_learnact.expertNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setExpertnames(String expertnames) {
        this.expertnames = expertnames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.teacherNames
     *
     * @return the value of t_learnact.teacherNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getTeachernames() {
        return teachernames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.teacherNames
     *
     * @param teachernames the value for t_learnact.teacherNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setTeachernames(String teachernames) {
        this.teachernames = teachernames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.studentNames
     *
     * @return the value of t_learnact.studentNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getStudentnames() {
        return studentnames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.studentNames
     *
     * @param studentnames the value for t_learnact.studentNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setStudentnames(String studentnames) {
        this.studentnames = studentnames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.actPlace
     *
     * @return the value of t_learnact.actPlace
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getActplace() {
        return actplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.actPlace
     *
     * @param actplace the value for t_learnact.actPlace
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setActplace(String actplace) {
        this.actplace = actplace;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.actTime
     *
     * @return the value of t_learnact.actTime
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getActtime() {
        return acttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.actTime
     *
     * @param acttime the value for t_learnact.actTime
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setActtime(String acttime) {
        this.acttime = acttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.subjects
     *
     * @return the value of t_learnact.subjects
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getSubjects() {
        return subjects;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.subjects
     *
     * @param subjects the value for t_learnact.subjects
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setSubjects(String subjects) {
        this.subjects = subjects;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_learnact.remark
     *
     * @return the value of t_learnact.remark
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_learnact.remark
     *
     * @param remark the value for t_learnact.remark
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}