package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TPaperExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public TPaperExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	protected TPaperExample(TPaperExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_paper
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andPaperidIsNull() {
			addCriterion("paperId is null");
			return this;
		}

		public Criteria andPaperidIsNotNull() {
			addCriterion("paperId is not null");
			return this;
		}

		public Criteria andPaperidEqualTo(Long value) {
			addCriterion("paperId =", value, "paperid");
			return this;
		}

		public Criteria andPaperidNotEqualTo(Long value) {
			addCriterion("paperId <>", value, "paperid");
			return this;
		}

		public Criteria andPaperidGreaterThan(Long value) {
			addCriterion("paperId >", value, "paperid");
			return this;
		}

		public Criteria andPaperidGreaterThanOrEqualTo(Long value) {
			addCriterion("paperId >=", value, "paperid");
			return this;
		}

		public Criteria andPaperidLessThan(Long value) {
			addCriterion("paperId <", value, "paperid");
			return this;
		}

		public Criteria andPaperidLessThanOrEqualTo(Long value) {
			addCriterion("paperId <=", value, "paperid");
			return this;
		}

		public Criteria andPaperidIn(List values) {
			addCriterion("paperId in", values, "paperid");
			return this;
		}

		public Criteria andPaperidNotIn(List values) {
			addCriterion("paperId not in", values, "paperid");
			return this;
		}

		public Criteria andPaperidBetween(Long value1, Long value2) {
			addCriterion("paperId between", value1, value2, "paperid");
			return this;
		}

		public Criteria andPaperidNotBetween(Long value1, Long value2) {
			addCriterion("paperId not between", value1, value2, "paperid");
			return this;
		}

		public Criteria andPapernameIsNull() {
			addCriterion("paperName is null");
			return this;
		}

		public Criteria andPapernameIsNotNull() {
			addCriterion("paperName is not null");
			return this;
		}

		public Criteria andPapernameEqualTo(String value) {
			addCriterion("paperName =", value, "papername");
			return this;
		}

		public Criteria andPapernameNotEqualTo(String value) {
			addCriterion("paperName <>", value, "papername");
			return this;
		}

		public Criteria andPapernameGreaterThan(String value) {
			addCriterion("paperName >", value, "papername");
			return this;
		}

		public Criteria andPapernameGreaterThanOrEqualTo(String value) {
			addCriterion("paperName >=", value, "papername");
			return this;
		}

		public Criteria andPapernameLessThan(String value) {
			addCriterion("paperName <", value, "papername");
			return this;
		}

		public Criteria andPapernameLessThanOrEqualTo(String value) {
			addCriterion("paperName <=", value, "papername");
			return this;
		}

		public Criteria andPapernameLike(String value) {
			addCriterion("paperName like", value, "papername");
			return this;
		}

		public Criteria andPapernameNotLike(String value) {
			addCriterion("paperName not like", value, "papername");
			return this;
		}

		public Criteria andPapernameIn(List values) {
			addCriterion("paperName in", values, "papername");
			return this;
		}

		public Criteria andPapernameNotIn(List values) {
			addCriterion("paperName not in", values, "papername");
			return this;
		}

		public Criteria andPapernameBetween(String value1, String value2) {
			addCriterion("paperName between", value1, value2, "papername");
			return this;
		}

		public Criteria andPapernameNotBetween(String value1, String value2) {
			addCriterion("paperName not between", value1, value2, "papername");
			return this;
		}

		public Criteria andPaperauthorIsNull() {
			addCriterion("paperAuthor is null");
			return this;
		}

		public Criteria andPaperauthorIsNotNull() {
			addCriterion("paperAuthor is not null");
			return this;
		}

		public Criteria andPaperauthorEqualTo(String value) {
			addCriterion("paperAuthor =", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorNotEqualTo(String value) {
			addCriterion("paperAuthor <>", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorGreaterThan(String value) {
			addCriterion("paperAuthor >", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorGreaterThanOrEqualTo(String value) {
			addCriterion("paperAuthor >=", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorLessThan(String value) {
			addCriterion("paperAuthor <", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorLessThanOrEqualTo(String value) {
			addCriterion("paperAuthor <=", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorLike(String value) {
			addCriterion("paperAuthor like", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorNotLike(String value) {
			addCriterion("paperAuthor not like", value, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorIn(List values) {
			addCriterion("paperAuthor in", values, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorNotIn(List values) {
			addCriterion("paperAuthor not in", values, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorBetween(String value1, String value2) {
			addCriterion("paperAuthor between", value1, value2, "paperauthor");
			return this;
		}

		public Criteria andPaperauthorNotBetween(String value1, String value2) {
			addCriterion("paperAuthor not between", value1, value2,
					"paperauthor");
			return this;
		}

		public Criteria andPapernotenameIsNull() {
			addCriterion("paperNoteName is null");
			return this;
		}

		public Criteria andPapernotenameIsNotNull() {
			addCriterion("paperNoteName is not null");
			return this;
		}

		public Criteria andPapernotenameEqualTo(String value) {
			addCriterion("paperNoteName =", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameNotEqualTo(String value) {
			addCriterion("paperNoteName <>", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameGreaterThan(String value) {
			addCriterion("paperNoteName >", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameGreaterThanOrEqualTo(String value) {
			addCriterion("paperNoteName >=", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameLessThan(String value) {
			addCriterion("paperNoteName <", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameLessThanOrEqualTo(String value) {
			addCriterion("paperNoteName <=", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameLike(String value) {
			addCriterion("paperNoteName like", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameNotLike(String value) {
			addCriterion("paperNoteName not like", value, "papernotename");
			return this;
		}

		public Criteria andPapernotenameIn(List values) {
			addCriterion("paperNoteName in", values, "papernotename");
			return this;
		}

		public Criteria andPapernotenameNotIn(List values) {
			addCriterion("paperNoteName not in", values, "papernotename");
			return this;
		}

		public Criteria andPapernotenameBetween(String value1, String value2) {
			addCriterion("paperNoteName between", value1, value2,
					"papernotename");
			return this;
		}

		public Criteria andPapernotenameNotBetween(String value1, String value2) {
			addCriterion("paperNoteName not between", value1, value2,
					"papernotename");
			return this;
		}

		public Criteria andPapernoteyearIsNull() {
			addCriterion("paperNoteYear is null");
			return this;
		}

		public Criteria andPapernoteyearIsNotNull() {
			addCriterion("paperNoteYear is not null");
			return this;
		}

		public Criteria andPapernoteyearEqualTo(String value) {
			addCriterion("paperNoteYear =", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearNotEqualTo(String value) {
			addCriterion("paperNoteYear <>", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearGreaterThan(String value) {
			addCriterion("paperNoteYear >", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearGreaterThanOrEqualTo(String value) {
			addCriterion("paperNoteYear >=", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearLessThan(String value) {
			addCriterion("paperNoteYear <", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearLessThanOrEqualTo(String value) {
			addCriterion("paperNoteYear <=", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearLike(String value) {
			addCriterion("paperNoteYear like", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearNotLike(String value) {
			addCriterion("paperNoteYear not like", value, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearIn(List values) {
			addCriterion("paperNoteYear in", values, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearNotIn(List values) {
			addCriterion("paperNoteYear not in", values, "papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearBetween(String value1, String value2) {
			addCriterion("paperNoteYear between", value1, value2,
					"papernoteyear");
			return this;
		}

		public Criteria andPapernoteyearNotBetween(String value1, String value2) {
			addCriterion("paperNoteYear not between", value1, value2,
					"papernoteyear");
			return this;
		}

		public Criteria andPapernotenoIsNull() {
			addCriterion("paperNoteNO is null");
			return this;
		}

		public Criteria andPapernotenoIsNotNull() {
			addCriterion("paperNoteNO is not null");
			return this;
		}

		public Criteria andPapernotenoEqualTo(String value) {
			addCriterion("paperNoteNO =", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoNotEqualTo(String value) {
			addCriterion("paperNoteNO <>", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoGreaterThan(String value) {
			addCriterion("paperNoteNO >", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoGreaterThanOrEqualTo(String value) {
			addCriterion("paperNoteNO >=", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoLessThan(String value) {
			addCriterion("paperNoteNO <", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoLessThanOrEqualTo(String value) {
			addCriterion("paperNoteNO <=", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoLike(String value) {
			addCriterion("paperNoteNO like", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoNotLike(String value) {
			addCriterion("paperNoteNO not like", value, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoIn(List values) {
			addCriterion("paperNoteNO in", values, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoNotIn(List values) {
			addCriterion("paperNoteNO not in", values, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoBetween(String value1, String value2) {
			addCriterion("paperNoteNO between", value1, value2, "papernoteno");
			return this;
		}

		public Criteria andPapernotenoNotBetween(String value1, String value2) {
			addCriterion("paperNoteNO not between", value1, value2,
					"papernoteno");
			return this;
		}

		public Criteria andPaperdownloadidIsNull() {
			addCriterion("paperDownloadId is null");
			return this;
		}

		public Criteria andPaperdownloadidIsNotNull() {
			addCriterion("paperDownloadId is not null");
			return this;
		}

		public Criteria andPaperdownloadidEqualTo(Long value) {
			addCriterion("paperDownloadId =", value, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidNotEqualTo(Long value) {
			addCriterion("paperDownloadId <>", value, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidGreaterThan(Long value) {
			addCriterion("paperDownloadId >", value, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidGreaterThanOrEqualTo(Long value) {
			addCriterion("paperDownloadId >=", value, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidLessThan(Long value) {
			addCriterion("paperDownloadId <", value, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidLessThanOrEqualTo(Long value) {
			addCriterion("paperDownloadId <=", value, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidIn(List values) {
			addCriterion("paperDownloadId in", values, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidNotIn(List values) {
			addCriterion("paperDownloadId not in", values, "paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidBetween(Long value1, Long value2) {
			addCriterion("paperDownloadId between", value1, value2,
					"paperdownloadid");
			return this;
		}

		public Criteria andPaperdownloadidNotBetween(Long value1, Long value2) {
			addCriterion("paperDownloadId not between", value1, value2,
					"paperdownloadid");
			return this;
		}

		public Criteria andPaperteacheridIsNull() {
			addCriterion("paperTeacherId is null");
			return this;
		}

		public Criteria andPaperteacheridIsNotNull() {
			addCriterion("paperTeacherId is not null");
			return this;
		}

		public Criteria andPaperteacheridEqualTo(Long value) {
			addCriterion("paperTeacherId =", value, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridNotEqualTo(Long value) {
			addCriterion("paperTeacherId <>", value, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridGreaterThan(Long value) {
			addCriterion("paperTeacherId >", value, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridGreaterThanOrEqualTo(Long value) {
			addCriterion("paperTeacherId >=", value, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridLessThan(Long value) {
			addCriterion("paperTeacherId <", value, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridLessThanOrEqualTo(Long value) {
			addCriterion("paperTeacherId <=", value, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridIn(List values) {
			addCriterion("paperTeacherId in", values, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridNotIn(List values) {
			addCriterion("paperTeacherId not in", values, "paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridBetween(Long value1, Long value2) {
			addCriterion("paperTeacherId between", value1, value2,
					"paperteacherid");
			return this;
		}

		public Criteria andPaperteacheridNotBetween(Long value1, Long value2) {
			addCriterion("paperTeacherId not between", value1, value2,
					"paperteacherid");
			return this;
		}

		public Criteria andPaperteachorresearchIsNull() {
			addCriterion("paperTeachOrResearch is null");
			return this;
		}

		public Criteria andPaperteachorresearchIsNotNull() {
			addCriterion("paperTeachOrResearch is not null");
			return this;
		}

		public Criteria andPaperteachorresearchEqualTo(String value) {
			addCriterion("paperTeachOrResearch =", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchNotEqualTo(String value) {
			addCriterion("paperTeachOrResearch <>", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchGreaterThan(String value) {
			addCriterion("paperTeachOrResearch >", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchGreaterThanOrEqualTo(String value) {
			addCriterion("paperTeachOrResearch >=", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchLessThan(String value) {
			addCriterion("paperTeachOrResearch <", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchLessThanOrEqualTo(String value) {
			addCriterion("paperTeachOrResearch <=", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchLike(String value) {
			addCriterion("paperTeachOrResearch like", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchNotLike(String value) {
			addCriterion("paperTeachOrResearch not like", value,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchIn(List values) {
			addCriterion("paperTeachOrResearch in", values,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchNotIn(List values) {
			addCriterion("paperTeachOrResearch not in", values,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchBetween(String value1,
				String value2) {
			addCriterion("paperTeachOrResearch between", value1, value2,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachorresearchNotBetween(String value1,
				String value2) {
			addCriterion("paperTeachOrResearch not between", value1, value2,
					"paperteachorresearch");
			return this;
		}

		public Criteria andPaperteachernameIsNull() {
			addCriterion("paperTeacherName is null");
			return this;
		}

		public Criteria andPaperteachernameIsNotNull() {
			addCriterion("paperTeacherName is not null");
			return this;
		}

		public Criteria andPaperteachernameEqualTo(String value) {
			addCriterion("paperTeacherName =", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameNotEqualTo(String value) {
			addCriterion("paperTeacherName <>", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameGreaterThan(String value) {
			addCriterion("paperTeacherName >", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameGreaterThanOrEqualTo(String value) {
			addCriterion("paperTeacherName >=", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameLessThan(String value) {
			addCriterion("paperTeacherName <", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameLessThanOrEqualTo(String value) {
			addCriterion("paperTeacherName <=", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameLike(String value) {
			addCriterion("paperTeacherName like", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameNotLike(String value) {
			addCriterion("paperTeacherName not like", value, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameIn(List values) {
			addCriterion("paperTeacherName in", values, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameNotIn(List values) {
			addCriterion("paperTeacherName not in", values, "paperteachername");
			return this;
		}

		public Criteria andPaperteachernameBetween(String value1, String value2) {
			addCriterion("paperTeacherName between", value1, value2,
					"paperteachername");
			return this;
		}

		public Criteria andPaperteachernameNotBetween(String value1,
				String value2) {
			addCriterion("paperTeacherName not between", value1, value2,
					"paperteachername");
			return this;
		}

		public Criteria andPapernotecountryIsNull() {
			addCriterion("paperNoteCountry is null");
			return this;
		}

		public Criteria andPapernotecountryIsNotNull() {
			addCriterion("paperNoteCountry is not null");
			return this;
		}

		public Criteria andPapernotecountryEqualTo(String value) {
			addCriterion("paperNoteCountry =", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryNotEqualTo(String value) {
			addCriterion("paperNoteCountry <>", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryGreaterThan(String value) {
			addCriterion("paperNoteCountry >", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryGreaterThanOrEqualTo(String value) {
			addCriterion("paperNoteCountry >=", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryLessThan(String value) {
			addCriterion("paperNoteCountry <", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryLessThanOrEqualTo(String value) {
			addCriterion("paperNoteCountry <=", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryLike(String value) {
			addCriterion("paperNoteCountry like", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryNotLike(String value) {
			addCriterion("paperNoteCountry not like", value, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryIn(List values) {
			addCriterion("paperNoteCountry in", values, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryNotIn(List values) {
			addCriterion("paperNoteCountry not in", values, "papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryBetween(String value1, String value2) {
			addCriterion("paperNoteCountry between", value1, value2,
					"papernotecountry");
			return this;
		}

		public Criteria andPapernotecountryNotBetween(String value1,
				String value2) {
			addCriterion("paperNoteCountry not between", value1, value2,
					"papernotecountry");
			return this;
		}

		public Criteria andPapernotedateIsNull() {
			addCriterion("paperNoteDate is null");
			return this;
		}

		public Criteria andPapernotedateIsNotNull() {
			addCriterion("paperNoteDate is not null");
			return this;
		}

		public Criteria andPapernotedateEqualTo(String value) {
			addCriterion("paperNoteDate =", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateNotEqualTo(String value) {
			addCriterion("paperNoteDate <>", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateGreaterThan(String value) {
			addCriterion("paperNoteDate >", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateGreaterThanOrEqualTo(String value) {
			addCriterion("paperNoteDate >=", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateLessThan(String value) {
			addCriterion("paperNoteDate <", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateLessThanOrEqualTo(String value) {
			addCriterion("paperNoteDate <=", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateLike(String value) {
			addCriterion("paperNoteDate like", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateNotLike(String value) {
			addCriterion("paperNoteDate not like", value, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateIn(List values) {
			addCriterion("paperNoteDate in", values, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateNotIn(List values) {
			addCriterion("paperNoteDate not in", values, "papernotedate");
			return this;
		}

		public Criteria andPapernotedateBetween(String value1, String value2) {
			addCriterion("paperNoteDate between", value1, value2,
					"papernotedate");
			return this;
		}

		public Criteria andPapernotedateNotBetween(String value1, String value2) {
			addCriterion("paperNoteDate not between", value1, value2,
					"papernotedate");
			return this;
		}

		public Criteria andPapernotepageIsNull() {
			addCriterion("paperNotePage is null");
			return this;
		}

		public Criteria andPapernotepageIsNotNull() {
			addCriterion("paperNotePage is not null");
			return this;
		}

		public Criteria andPapernotepageEqualTo(String value) {
			addCriterion("paperNotePage =", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageNotEqualTo(String value) {
			addCriterion("paperNotePage <>", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageGreaterThan(String value) {
			addCriterion("paperNotePage >", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageGreaterThanOrEqualTo(String value) {
			addCriterion("paperNotePage >=", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageLessThan(String value) {
			addCriterion("paperNotePage <", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageLessThanOrEqualTo(String value) {
			addCriterion("paperNotePage <=", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageLike(String value) {
			addCriterion("paperNotePage like", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageNotLike(String value) {
			addCriterion("paperNotePage not like", value, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageIn(List values) {
			addCriterion("paperNotePage in", values, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageNotIn(List values) {
			addCriterion("paperNotePage not in", values, "papernotepage");
			return this;
		}

		public Criteria andPapernotepageBetween(String value1, String value2) {
			addCriterion("paperNotePage between", value1, value2,
					"papernotepage");
			return this;
		}

		public Criteria andPapernotepageNotBetween(String value1, String value2) {
			addCriterion("paperNotePage not between", value1, value2,
					"papernotepage");
			return this;
		}

		public Criteria andPaperincludedIsNull() {
			addCriterion("paperIncluded is null");
			return this;
		}

		public Criteria andPaperincludedIsNotNull() {
			addCriterion("paperIncluded is not null");
			return this;
		}

		public Criteria andPaperincludedEqualTo(String value) {
			addCriterion("paperIncluded =", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedNotEqualTo(String value) {
			addCriterion("paperIncluded <>", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedGreaterThan(String value) {
			addCriterion("paperIncluded >", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedGreaterThanOrEqualTo(String value) {
			addCriterion("paperIncluded >=", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedLessThan(String value) {
			addCriterion("paperIncluded <", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedLessThanOrEqualTo(String value) {
			addCriterion("paperIncluded <=", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedLike(String value) {
			addCriterion("paperIncluded like", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedNotLike(String value) {
			addCriterion("paperIncluded not like", value, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedIn(List values) {
			addCriterion("paperIncluded in", values, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedNotIn(List values) {
			addCriterion("paperIncluded not in", values, "paperincluded");
			return this;
		}

		public Criteria andPaperincludedBetween(String value1, String value2) {
			addCriterion("paperIncluded between", value1, value2,
					"paperincluded");
			return this;
		}

		public Criteria andPaperincludedNotBetween(String value1, String value2) {
			addCriterion("paperIncluded not between", value1, value2,
					"paperincluded");
			return this;
		}

		public Criteria andPaperfactorsIsNull() {
			addCriterion("paperFactors is null");
			return this;
		}

		public Criteria andPaperfactorsIsNotNull() {
			addCriterion("paperFactors is not null");
			return this;
		}

		public Criteria andPaperfactorsEqualTo(String value) {
			addCriterion("paperFactors =", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsNotEqualTo(String value) {
			addCriterion("paperFactors <>", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsGreaterThan(String value) {
			addCriterion("paperFactors >", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsGreaterThanOrEqualTo(String value) {
			addCriterion("paperFactors >=", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsLessThan(String value) {
			addCriterion("paperFactors <", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsLessThanOrEqualTo(String value) {
			addCriterion("paperFactors <=", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsLike(String value) {
			addCriterion("paperFactors like", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsNotLike(String value) {
			addCriterion("paperFactors not like", value, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsIn(List values) {
			addCriterion("paperFactors in", values, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsNotIn(List values) {
			addCriterion("paperFactors not in", values, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsBetween(String value1, String value2) {
			addCriterion("paperFactors between", value1, value2, "paperfactors");
			return this;
		}

		public Criteria andPaperfactorsNotBetween(String value1, String value2) {
			addCriterion("paperFactors not between", value1, value2,
					"paperfactors");
			return this;
		}

		public Criteria andPaperreprintIsNull() {
			addCriterion("paperReprint is null");
			return this;
		}

		public Criteria andPaperreprintIsNotNull() {
			addCriterion("paperReprint is not null");
			return this;
		}

		public Criteria andPaperreprintEqualTo(String value) {
			addCriterion("paperReprint =", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintNotEqualTo(String value) {
			addCriterion("paperReprint <>", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintGreaterThan(String value) {
			addCriterion("paperReprint >", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintGreaterThanOrEqualTo(String value) {
			addCriterion("paperReprint >=", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintLessThan(String value) {
			addCriterion("paperReprint <", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintLessThanOrEqualTo(String value) {
			addCriterion("paperReprint <=", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintLike(String value) {
			addCriterion("paperReprint like", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintNotLike(String value) {
			addCriterion("paperReprint not like", value, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintIn(List values) {
			addCriterion("paperReprint in", values, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintNotIn(List values) {
			addCriterion("paperReprint not in", values, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintBetween(String value1, String value2) {
			addCriterion("paperReprint between", value1, value2, "paperreprint");
			return this;
		}

		public Criteria andPaperreprintNotBetween(String value1, String value2) {
			addCriterion("paperReprint not between", value1, value2,
					"paperreprint");
			return this;
		}

		public Criteria andPaperclassaIsNull() {
			addCriterion("paperClassA is null");
			return this;
		}

		public Criteria andPaperclassaIsNotNull() {
			addCriterion("paperClassA is not null");
			return this;
		}

		public Criteria andPaperclassaEqualTo(String value) {
			addCriterion("paperClassA =", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaNotEqualTo(String value) {
			addCriterion("paperClassA <>", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaGreaterThan(String value) {
			addCriterion("paperClassA >", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaGreaterThanOrEqualTo(String value) {
			addCriterion("paperClassA >=", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaLessThan(String value) {
			addCriterion("paperClassA <", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaLessThanOrEqualTo(String value) {
			addCriterion("paperClassA <=", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaLike(String value) {
			addCriterion("paperClassA like", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaNotLike(String value) {
			addCriterion("paperClassA not like", value, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaIn(List values) {
			addCriterion("paperClassA in", values, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaNotIn(List values) {
			addCriterion("paperClassA not in", values, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaBetween(String value1, String value2) {
			addCriterion("paperClassA between", value1, value2, "paperclassa");
			return this;
		}

		public Criteria andPaperclassaNotBetween(String value1, String value2) {
			addCriterion("paperClassA not between", value1, value2,
					"paperclassa");
			return this;
		}

		public Criteria andPaperprojectnoIsNull() {
			addCriterion("paperProjectNO is null");
			return this;
		}

		public Criteria andPaperprojectnoIsNotNull() {
			addCriterion("paperProjectNO is not null");
			return this;
		}

		public Criteria andPaperprojectnoEqualTo(String value) {
			addCriterion("paperProjectNO =", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoNotEqualTo(String value) {
			addCriterion("paperProjectNO <>", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoGreaterThan(String value) {
			addCriterion("paperProjectNO >", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoGreaterThanOrEqualTo(String value) {
			addCriterion("paperProjectNO >=", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoLessThan(String value) {
			addCriterion("paperProjectNO <", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoLessThanOrEqualTo(String value) {
			addCriterion("paperProjectNO <=", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoLike(String value) {
			addCriterion("paperProjectNO like", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoNotLike(String value) {
			addCriterion("paperProjectNO not like", value, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoIn(List values) {
			addCriterion("paperProjectNO in", values, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoNotIn(List values) {
			addCriterion("paperProjectNO not in", values, "paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoBetween(String value1, String value2) {
			addCriterion("paperProjectNO between", value1, value2,
					"paperprojectno");
			return this;
		}

		public Criteria andPaperprojectnoNotBetween(String value1, String value2) {
			addCriterion("paperProjectNO not between", value1, value2,
					"paperprojectno");
			return this;
		}
	}
}