package com.et59.cus.domain.entity;

public class TPrize {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeId
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private Long prizeid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeType
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private String prizetype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeInfo
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private String prizeinfo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeDate
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private String prizedate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeTeacherId
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private Long prizeteacherid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeTeachOrResearch
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private String prizeteachorresearch;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeTeacherName
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private String prizeteachername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_prize.prizeRank
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	private String prizerank;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeId
	 * @return  the value of t_prize.prizeId
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public Long getPrizeid() {
		return prizeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeId
	 * @param prizeid  the value for t_prize.prizeId
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizeid(Long prizeid) {
		this.prizeid = prizeid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeType
	 * @return  the value of t_prize.prizeType
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getPrizetype() {
		return prizetype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeType
	 * @param prizetype  the value for t_prize.prizeType
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizetype(String prizetype) {
		this.prizetype = prizetype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeInfo
	 * @return  the value of t_prize.prizeInfo
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getPrizeinfo() {
		return prizeinfo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeInfo
	 * @param prizeinfo  the value for t_prize.prizeInfo
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizeinfo(String prizeinfo) {
		this.prizeinfo = prizeinfo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeDate
	 * @return  the value of t_prize.prizeDate
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getPrizedate() {
		return prizedate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeDate
	 * @param prizedate  the value for t_prize.prizeDate
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizedate(String prizedate) {
		this.prizedate = prizedate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeTeacherId
	 * @return  the value of t_prize.prizeTeacherId
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public Long getPrizeteacherid() {
		return prizeteacherid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeTeacherId
	 * @param prizeteacherid  the value for t_prize.prizeTeacherId
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizeteacherid(Long prizeteacherid) {
		this.prizeteacherid = prizeteacherid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeTeachOrResearch
	 * @return  the value of t_prize.prizeTeachOrResearch
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getPrizeteachorresearch() {
		return prizeteachorresearch;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeTeachOrResearch
	 * @param prizeteachorresearch  the value for t_prize.prizeTeachOrResearch
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizeteachorresearch(String prizeteachorresearch) {
		this.prizeteachorresearch = prizeteachorresearch;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeTeacherName
	 * @return  the value of t_prize.prizeTeacherName
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getPrizeteachername() {
		return prizeteachername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeTeacherName
	 * @param prizeteachername  the value for t_prize.prizeTeacherName
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizeteachername(String prizeteachername) {
		this.prizeteachername = prizeteachername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_prize.prizeRank
	 * @return  the value of t_prize.prizeRank
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getPrizerank() {
		return prizerank;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_prize.prizeRank
	 * @param prizerank  the value for t_prize.prizeRank
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setPrizerank(String prizerank) {
		this.prizerank = prizerank;
	}
}