package com.et59.cus.domain.entity;

import java.util.Date;

public class TResearch {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchId
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private Long researchid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchLevel
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private String researchlevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchName
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private String researchname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchMoney
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private Integer researchmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchMatchMoney
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private Integer researchmatchmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchHost
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private String researchhost;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchActor
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private String researchactor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchBeginDate
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private Date researchbegindate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.researchEndDate
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private Date researchenddate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_research.downloadId
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    private Long downloadid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchId
     *
     * @return the value of t_research.researchId
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public Long getResearchid() {
        return researchid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchId
     *
     * @param researchid the value for t_research.researchId
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchid(Long researchid) {
        this.researchid = researchid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchLevel
     *
     * @return the value of t_research.researchLevel
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public String getResearchlevel() {
        return researchlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchLevel
     *
     * @param researchlevel the value for t_research.researchLevel
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchlevel(String researchlevel) {
        this.researchlevel = researchlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchName
     *
     * @return the value of t_research.researchName
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public String getResearchname() {
        return researchname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchName
     *
     * @param researchname the value for t_research.researchName
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchname(String researchname) {
        this.researchname = researchname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchMoney
     *
     * @return the value of t_research.researchMoney
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public Integer getResearchmoney() {
        return researchmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchMoney
     *
     * @param researchmoney the value for t_research.researchMoney
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchmoney(Integer researchmoney) {
        this.researchmoney = researchmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchMatchMoney
     *
     * @return the value of t_research.researchMatchMoney
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public Integer getResearchmatchmoney() {
        return researchmatchmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchMatchMoney
     *
     * @param researchmatchmoney the value for t_research.researchMatchMoney
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchmatchmoney(Integer researchmatchmoney) {
        this.researchmatchmoney = researchmatchmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchHost
     *
     * @return the value of t_research.researchHost
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public String getResearchhost() {
        return researchhost;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchHost
     *
     * @param researchhost the value for t_research.researchHost
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchhost(String researchhost) {
        this.researchhost = researchhost;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchActor
     *
     * @return the value of t_research.researchActor
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public String getResearchactor() {
        return researchactor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchActor
     *
     * @param researchactor the value for t_research.researchActor
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchactor(String researchactor) {
        this.researchactor = researchactor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchBeginDate
     *
     * @return the value of t_research.researchBeginDate
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public Date getResearchbegindate() {
        return researchbegindate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchBeginDate
     *
     * @param researchbegindate the value for t_research.researchBeginDate
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchbegindate(Date researchbegindate) {
        this.researchbegindate = researchbegindate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.researchEndDate
     *
     * @return the value of t_research.researchEndDate
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public Date getResearchenddate() {
        return researchenddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.researchEndDate
     *
     * @param researchenddate the value for t_research.researchEndDate
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setResearchenddate(Date researchenddate) {
        this.researchenddate = researchenddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_research.downloadId
     *
     * @return the value of t_research.downloadId
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public Long getDownloadid() {
        return downloadid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_research.downloadId
     *
     * @param downloadid the value for t_research.downloadId
     *
     * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
     */
    public void setDownloadid(Long downloadid) {
        this.downloadid = downloadid;
    }
}