package com.et59.cus.domain.entity;

public class TResearch {
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private Long researchid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchNO
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchLevel
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchlevel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchName
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchMoney
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private Integer researchmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchMatchMoney
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private Integer researchmatchmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchHost
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchhost;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchActor
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchactor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchBeginDate
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchbegindate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchEndDate
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchenddate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.downloadId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private Long downloadid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchTeacherId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private Long researchteacherid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_research.researchTeachOrResearch
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	private String researchteachorresearch;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchId
	 * @return  the value of t_research.researchId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public Long getResearchid() {
		return researchid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchId
	 * @param researchid  the value for t_research.researchId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchid(Long researchid) {
		this.researchid = researchid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchNO
	 * @return  the value of t_research.researchNO
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchno() {
		return researchno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchNO
	 * @param researchno  the value for t_research.researchNO
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchno(String researchno) {
		this.researchno = researchno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchLevel
	 * @return  the value of t_research.researchLevel
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchlevel() {
		return researchlevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchLevel
	 * @param researchlevel  the value for t_research.researchLevel
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchlevel(String researchlevel) {
		this.researchlevel = researchlevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchName
	 * @return  the value of t_research.researchName
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchname() {
		return researchname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchName
	 * @param researchname  the value for t_research.researchName
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchname(String researchname) {
		this.researchname = researchname;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchHost
	 * @return  the value of t_research.researchHost
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchhost() {
		return researchhost;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchHost
	 * @param researchhost  the value for t_research.researchHost
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchhost(String researchhost) {
		this.researchhost = researchhost;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchActor
	 * @return  the value of t_research.researchActor
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchactor() {
		return researchactor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchActor
	 * @param researchactor  the value for t_research.researchActor
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchactor(String researchactor) {
		this.researchactor = researchactor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchBeginDate
	 * @return  the value of t_research.researchBeginDate
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchbegindate() {
		return researchbegindate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchBeginDate
	 * @param researchbegindate  the value for t_research.researchBeginDate
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchbegindate(String researchbegindate) {
		this.researchbegindate = researchbegindate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchEndDate
	 * @return  the value of t_research.researchEndDate
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchenddate() {
		return researchenddate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchEndDate
	 * @param researchenddate  the value for t_research.researchEndDate
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchenddate(String researchenddate) {
		this.researchenddate = researchenddate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.downloadId
	 * @return  the value of t_research.downloadId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public Long getDownloadid() {
		return downloadid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.downloadId
	 * @param downloadid  the value for t_research.downloadId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setDownloadid(Long downloadid) {
		this.downloadid = downloadid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchTeacherId
	 * @return  the value of t_research.researchTeacherId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public Long getResearchteacherid() {
		return researchteacherid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchTeacherId
	 * @param researchteacherid  the value for t_research.researchTeacherId
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchteacherid(Long researchteacherid) {
		this.researchteacherid = researchteacherid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_research.researchTeachOrResearch
	 * @return  the value of t_research.researchTeachOrResearch
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public String getResearchteachorresearch() {
		return researchteachorresearch;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_research.researchTeachOrResearch
	 * @param researchteachorresearch  the value for t_research.researchTeachOrResearch
	 * @ibatorgenerated  Sat May 16 18:50:10 CST 2015
	 */
	public void setResearchteachorresearch(String researchteachorresearch) {
		this.researchteachorresearch = researchteachorresearch;
	}

	public int getResearchmoney() {
		return researchmoney;
	}

	public void setResearchmoney(int researchmoney) {
		this.researchmoney = researchmoney;
	}

	public int getResearchmatchmoney() {
		return researchmatchmoney;
	}

	public void setResearchmatchmoney(int researchmatchmoney) {
		this.researchmatchmoney = researchmatchmoney;
	}

}