package com.et59.cus.domain.entity;

public class TSocialevent {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.eventId
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private Long eventid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.eventTime
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String eventtime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.eventPlace
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String eventplace;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.eventName
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String eventname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.eventType
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String eventtype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.students
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String students;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.isTogether
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String istogether;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.unitName
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String unitname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.teacherNames
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String teachernames;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.webSite
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String website;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_socialevent.remark
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.eventId
	 * @return  the value of t_socialevent.eventId
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public Long getEventid() {
		return eventid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.eventId
	 * @param eventid  the value for t_socialevent.eventId
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setEventid(Long eventid) {
		this.eventid = eventid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.eventTime
	 * @return  the value of t_socialevent.eventTime
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getEventtime() {
		return eventtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.eventTime
	 * @param eventtime  the value for t_socialevent.eventTime
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setEventtime(String eventtime) {
		this.eventtime = eventtime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.eventPlace
	 * @return  the value of t_socialevent.eventPlace
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getEventplace() {
		return eventplace;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.eventPlace
	 * @param eventplace  the value for t_socialevent.eventPlace
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setEventplace(String eventplace) {
		this.eventplace = eventplace;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.eventName
	 * @return  the value of t_socialevent.eventName
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getEventname() {
		return eventname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.eventName
	 * @param eventname  the value for t_socialevent.eventName
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setEventname(String eventname) {
		this.eventname = eventname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.eventType
	 * @return  the value of t_socialevent.eventType
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getEventtype() {
		return eventtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.eventType
	 * @param eventtype  the value for t_socialevent.eventType
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setEventtype(String eventtype) {
		this.eventtype = eventtype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.students
	 * @return  the value of t_socialevent.students
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getStudents() {
		return students;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.students
	 * @param students  the value for t_socialevent.students
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setStudents(String students) {
		this.students = students;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.isTogether
	 * @return  the value of t_socialevent.isTogether
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getIstogether() {
		return istogether;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.isTogether
	 * @param istogether  the value for t_socialevent.isTogether
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setIstogether(String istogether) {
		this.istogether = istogether;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.unitName
	 * @return  the value of t_socialevent.unitName
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getUnitname() {
		return unitname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.unitName
	 * @param unitname  the value for t_socialevent.unitName
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.teacherNames
	 * @return  the value of t_socialevent.teacherNames
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getTeachernames() {
		return teachernames;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.teacherNames
	 * @param teachernames  the value for t_socialevent.teacherNames
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setTeachernames(String teachernames) {
		this.teachernames = teachernames;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.webSite
	 * @return  the value of t_socialevent.webSite
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.webSite
	 * @param website  the value for t_socialevent.webSite
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_socialevent.remark
	 * @return  the value of t_socialevent.remark
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_socialevent.remark
	 * @param remark  the value for t_socialevent.remark
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}