package com.et59.cus.domain.entity;

public class TStudentaward {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.awardId
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private Long awardid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.stuName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String stuname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.stuNo
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String stuno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.stuProfession
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String stuprofession;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.awardName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String awardname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.awardType
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String awardtype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.grantTime
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String granttime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.grantOrg
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String grantorg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.teacherNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String teachernames;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_studentaward.remark
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private String remark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.awardId
     *
     * @return the value of t_studentaward.awardId
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public Long getAwardid() {
        return awardid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.awardId
     *
     * @param awardid the value for t_studentaward.awardId
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setAwardid(Long awardid) {
        this.awardid = awardid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.stuName
     *
     * @return the value of t_studentaward.stuName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.stuName
     *
     * @param stuname the value for t_studentaward.stuName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setStuname(String stuname) {
        this.stuname = stuname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.stuNo
     *
     * @return the value of t_studentaward.stuNo
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getStuno() {
        return stuno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.stuNo
     *
     * @param stuno the value for t_studentaward.stuNo
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setStuno(String stuno) {
        this.stuno = stuno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.stuProfession
     *
     * @return the value of t_studentaward.stuProfession
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getStuprofession() {
        return stuprofession;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.stuProfession
     *
     * @param stuprofession the value for t_studentaward.stuProfession
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setStuprofession(String stuprofession) {
        this.stuprofession = stuprofession;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.awardName
     *
     * @return the value of t_studentaward.awardName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getAwardname() {
        return awardname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.awardName
     *
     * @param awardname the value for t_studentaward.awardName
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setAwardname(String awardname) {
        this.awardname = awardname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.awardType
     *
     * @return the value of t_studentaward.awardType
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getAwardtype() {
        return awardtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.awardType
     *
     * @param awardtype the value for t_studentaward.awardType
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setAwardtype(String awardtype) {
        this.awardtype = awardtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.grantTime
     *
     * @return the value of t_studentaward.grantTime
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getGranttime() {
        return granttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.grantTime
     *
     * @param granttime the value for t_studentaward.grantTime
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setGranttime(String granttime) {
        this.granttime = granttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.grantOrg
     *
     * @return the value of t_studentaward.grantOrg
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getGrantorg() {
        return grantorg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.grantOrg
     *
     * @param grantorg the value for t_studentaward.grantOrg
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setGrantorg(String grantorg) {
        this.grantorg = grantorg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.teacherNames
     *
     * @return the value of t_studentaward.teacherNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getTeachernames() {
        return teachernames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.teacherNames
     *
     * @param teachernames the value for t_studentaward.teacherNames
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setTeachernames(String teachernames) {
        this.teachernames = teachernames;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_studentaward.remark
     *
     * @return the value of t_studentaward.remark
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_studentaward.remark
     *
     * @param remark the value for t_studentaward.remark
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}