package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSubjectExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public TSubjectExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	protected TSubjectExample(TSubjectExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Apr 29 16:15:22 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andSubjectidIsNull() {
			addCriterion("subjectId is null");
			return this;
		}

		public Criteria andSubjectidIsNotNull() {
			addCriterion("subjectId is not null");
			return this;
		}

		public Criteria andSubjectidEqualTo(Long value) {
			addCriterion("subjectId =", value, "subjectid");
			return this;
		}

		public Criteria andSubjectidNotEqualTo(Long value) {
			addCriterion("subjectId <>", value, "subjectid");
			return this;
		}

		public Criteria andSubjectidGreaterThan(Long value) {
			addCriterion("subjectId >", value, "subjectid");
			return this;
		}

		public Criteria andSubjectidGreaterThanOrEqualTo(Long value) {
			addCriterion("subjectId >=", value, "subjectid");
			return this;
		}

		public Criteria andSubjectidLessThan(Long value) {
			addCriterion("subjectId <", value, "subjectid");
			return this;
		}

		public Criteria andSubjectidLessThanOrEqualTo(Long value) {
			addCriterion("subjectId <=", value, "subjectid");
			return this;
		}

		public Criteria andSubjectidIn(List values) {
			addCriterion("subjectId in", values, "subjectid");
			return this;
		}

		public Criteria andSubjectidNotIn(List values) {
			addCriterion("subjectId not in", values, "subjectid");
			return this;
		}

		public Criteria andSubjectidBetween(Long value1, Long value2) {
			addCriterion("subjectId between", value1, value2, "subjectid");
			return this;
		}

		public Criteria andSubjectidNotBetween(Long value1, Long value2) {
			addCriterion("subjectId not between", value1, value2, "subjectid");
			return this;
		}

		public Criteria andSubjectnameIsNull() {
			addCriterion("subjectName is null");
			return this;
		}

		public Criteria andSubjectnameIsNotNull() {
			addCriterion("subjectName is not null");
			return this;
		}

		public Criteria andSubjectnameEqualTo(String value) {
			addCriterion("subjectName =", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotEqualTo(String value) {
			addCriterion("subjectName <>", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameGreaterThan(String value) {
			addCriterion("subjectName >", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameGreaterThanOrEqualTo(String value) {
			addCriterion("subjectName >=", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameLessThan(String value) {
			addCriterion("subjectName <", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameLessThanOrEqualTo(String value) {
			addCriterion("subjectName <=", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameLike(String value) {
			addCriterion("subjectName like", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotLike(String value) {
			addCriterion("subjectName not like", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameIn(List values) {
			addCriterion("subjectName in", values, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotIn(List values) {
			addCriterion("subjectName not in", values, "subjectname");
			return this;
		}

		public Criteria andSubjectnameBetween(String value1, String value2) {
			addCriterion("subjectName between", value1, value2, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotBetween(String value1, String value2) {
			addCriterion("subjectName not between", value1, value2,
					"subjectname");
			return this;
		}

		public Criteria andSubjecttextIsNull() {
			addCriterion("subjectText is null");
			return this;
		}

		public Criteria andSubjecttextIsNotNull() {
			addCriterion("subjectText is not null");
			return this;
		}

		public Criteria andSubjecttextEqualTo(String value) {
			addCriterion("subjectText =", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotEqualTo(String value) {
			addCriterion("subjectText <>", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextGreaterThan(String value) {
			addCriterion("subjectText >", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextGreaterThanOrEqualTo(String value) {
			addCriterion("subjectText >=", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextLessThan(String value) {
			addCriterion("subjectText <", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextLessThanOrEqualTo(String value) {
			addCriterion("subjectText <=", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextLike(String value) {
			addCriterion("subjectText like", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotLike(String value) {
			addCriterion("subjectText not like", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextIn(List values) {
			addCriterion("subjectText in", values, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotIn(List values) {
			addCriterion("subjectText not in", values, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextBetween(String value1, String value2) {
			addCriterion("subjectText between", value1, value2, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotBetween(String value1, String value2) {
			addCriterion("subjectText not between", value1, value2,
					"subjecttext");
			return this;
		}

		public Criteria andSubjecttypeIsNull() {
			addCriterion("subjectType is null");
			return this;
		}

		public Criteria andSubjecttypeIsNotNull() {
			addCriterion("subjectType is not null");
			return this;
		}

		public Criteria andSubjecttypeEqualTo(String value) {
			addCriterion("subjectType =", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotEqualTo(String value) {
			addCriterion("subjectType <>", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeGreaterThan(String value) {
			addCriterion("subjectType >", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeGreaterThanOrEqualTo(String value) {
			addCriterion("subjectType >=", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeLessThan(String value) {
			addCriterion("subjectType <", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeLessThanOrEqualTo(String value) {
			addCriterion("subjectType <=", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeLike(String value) {
			addCriterion("subjectType like", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotLike(String value) {
			addCriterion("subjectType not like", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeIn(List values) {
			addCriterion("subjectType in", values, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotIn(List values) {
			addCriterion("subjectType not in", values, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeBetween(String value1, String value2) {
			addCriterion("subjectType between", value1, value2, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotBetween(String value1, String value2) {
			addCriterion("subjectType not between", value1, value2,
					"subjecttype");
			return this;
		}

		public Criteria andSubjecttypenameIsNull() {
			addCriterion("subjectTypeName is null");
			return this;
		}

		public Criteria andSubjecttypenameIsNotNull() {
			addCriterion("subjectTypeName is not null");
			return this;
		}

		public Criteria andSubjecttypenameEqualTo(String value) {
			addCriterion("subjectTypeName =", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotEqualTo(String value) {
			addCriterion("subjectTypeName <>", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameGreaterThan(String value) {
			addCriterion("subjectTypeName >", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameGreaterThanOrEqualTo(String value) {
			addCriterion("subjectTypeName >=", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameLessThan(String value) {
			addCriterion("subjectTypeName <", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameLessThanOrEqualTo(String value) {
			addCriterion("subjectTypeName <=", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameLike(String value) {
			addCriterion("subjectTypeName like", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotLike(String value) {
			addCriterion("subjectTypeName not like", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameIn(List values) {
			addCriterion("subjectTypeName in", values, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotIn(List values) {
			addCriterion("subjectTypeName not in", values, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameBetween(String value1, String value2) {
			addCriterion("subjectTypeName between", value1, value2,
					"subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotBetween(String value1,
				String value2) {
			addCriterion("subjectTypeName not between", value1, value2,
					"subjecttypename");
			return this;
		}

		public Criteria andSubjectnoIsNull() {
			addCriterion("subjectNO is null");
			return this;
		}

		public Criteria andSubjectnoIsNotNull() {
			addCriterion("subjectNO is not null");
			return this;
		}

		public Criteria andSubjectnoEqualTo(String value) {
			addCriterion("subjectNO =", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoNotEqualTo(String value) {
			addCriterion("subjectNO <>", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoGreaterThan(String value) {
			addCriterion("subjectNO >", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoGreaterThanOrEqualTo(String value) {
			addCriterion("subjectNO >=", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoLessThan(String value) {
			addCriterion("subjectNO <", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoLessThanOrEqualTo(String value) {
			addCriterion("subjectNO <=", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoLike(String value) {
			addCriterion("subjectNO like", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoNotLike(String value) {
			addCriterion("subjectNO not like", value, "subjectno");
			return this;
		}

		public Criteria andSubjectnoIn(List values) {
			addCriterion("subjectNO in", values, "subjectno");
			return this;
		}

		public Criteria andSubjectnoNotIn(List values) {
			addCriterion("subjectNO not in", values, "subjectno");
			return this;
		}

		public Criteria andSubjectnoBetween(String value1, String value2) {
			addCriterion("subjectNO between", value1, value2, "subjectno");
			return this;
		}

		public Criteria andSubjectnoNotBetween(String value1, String value2) {
			addCriterion("subjectNO not between", value1, value2, "subjectno");
			return this;
		}

		public Criteria andSubjectoutlineIsNull() {
			addCriterion("subjectOutline is null");
			return this;
		}

		public Criteria andSubjectoutlineIsNotNull() {
			addCriterion("subjectOutline is not null");
			return this;
		}

		public Criteria andSubjectoutlineEqualTo(Long value) {
			addCriterion("subjectOutline =", value, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineNotEqualTo(Long value) {
			addCriterion("subjectOutline <>", value, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineGreaterThan(Long value) {
			addCriterion("subjectOutline >", value, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineGreaterThanOrEqualTo(Long value) {
			addCriterion("subjectOutline >=", value, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineLessThan(Long value) {
			addCriterion("subjectOutline <", value, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineLessThanOrEqualTo(Long value) {
			addCriterion("subjectOutline <=", value, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineIn(List values) {
			addCriterion("subjectOutline in", values, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineNotIn(List values) {
			addCriterion("subjectOutline not in", values, "subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineBetween(Long value1, Long value2) {
			addCriterion("subjectOutline between", value1, value2,
					"subjectoutline");
			return this;
		}

		public Criteria andSubjectoutlineNotBetween(Long value1, Long value2) {
			addCriterion("subjectOutline not between", value1, value2,
					"subjectoutline");
			return this;
		}

		public Criteria andSubjectscheduleIsNull() {
			addCriterion("subjectSchedule is null");
			return this;
		}

		public Criteria andSubjectscheduleIsNotNull() {
			addCriterion("subjectSchedule is not null");
			return this;
		}

		public Criteria andSubjectscheduleEqualTo(Long value) {
			addCriterion("subjectSchedule =", value, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleNotEqualTo(Long value) {
			addCriterion("subjectSchedule <>", value, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleGreaterThan(Long value) {
			addCriterion("subjectSchedule >", value, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleGreaterThanOrEqualTo(Long value) {
			addCriterion("subjectSchedule >=", value, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleLessThan(Long value) {
			addCriterion("subjectSchedule <", value, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleLessThanOrEqualTo(Long value) {
			addCriterion("subjectSchedule <=", value, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleIn(List values) {
			addCriterion("subjectSchedule in", values, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleNotIn(List values) {
			addCriterion("subjectSchedule not in", values, "subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleBetween(Long value1, Long value2) {
			addCriterion("subjectSchedule between", value1, value2,
					"subjectschedule");
			return this;
		}

		public Criteria andSubjectscheduleNotBetween(Long value1, Long value2) {
			addCriterion("subjectSchedule not between", value1, value2,
					"subjectschedule");
			return this;
		}

		public Criteria andSubjectinfoIsNull() {
			addCriterion("subjectInfo is null");
			return this;
		}

		public Criteria andSubjectinfoIsNotNull() {
			addCriterion("subjectInfo is not null");
			return this;
		}

		public Criteria andSubjectinfoEqualTo(Long value) {
			addCriterion("subjectInfo =", value, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoNotEqualTo(Long value) {
			addCriterion("subjectInfo <>", value, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoGreaterThan(Long value) {
			addCriterion("subjectInfo >", value, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoGreaterThanOrEqualTo(Long value) {
			addCriterion("subjectInfo >=", value, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoLessThan(Long value) {
			addCriterion("subjectInfo <", value, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoLessThanOrEqualTo(Long value) {
			addCriterion("subjectInfo <=", value, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoIn(List values) {
			addCriterion("subjectInfo in", values, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoNotIn(List values) {
			addCriterion("subjectInfo not in", values, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoBetween(Long value1, Long value2) {
			addCriterion("subjectInfo between", value1, value2, "subjectinfo");
			return this;
		}

		public Criteria andSubjectinfoNotBetween(Long value1, Long value2) {
			addCriterion("subjectInfo not between", value1, value2,
					"subjectinfo");
			return this;
		}

		public Criteria andSubjectisvalidIsNull() {
			addCriterion("subjectIsvalid is null");
			return this;
		}

		public Criteria andSubjectisvalidIsNotNull() {
			addCriterion("subjectIsvalid is not null");
			return this;
		}

		public Criteria andSubjectisvalidEqualTo(String value) {
			addCriterion("subjectIsvalid =", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotEqualTo(String value) {
			addCriterion("subjectIsvalid <>", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidGreaterThan(String value) {
			addCriterion("subjectIsvalid >", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidGreaterThanOrEqualTo(String value) {
			addCriterion("subjectIsvalid >=", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidLessThan(String value) {
			addCriterion("subjectIsvalid <", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidLessThanOrEqualTo(String value) {
			addCriterion("subjectIsvalid <=", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidLike(String value) {
			addCriterion("subjectIsvalid like", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotLike(String value) {
			addCriterion("subjectIsvalid not like", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidIn(List values) {
			addCriterion("subjectIsvalid in", values, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotIn(List values) {
			addCriterion("subjectIsvalid not in", values, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidBetween(String value1, String value2) {
			addCriterion("subjectIsvalid between", value1, value2,
					"subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotBetween(String value1, String value2) {
			addCriterion("subjectIsvalid not between", value1, value2,
					"subjectisvalid");
			return this;
		}

		public Criteria andSubjectteachernameIsNull() {
			addCriterion("subjectTeacherName is null");
			return this;
		}

		public Criteria andSubjectteachernameIsNotNull() {
			addCriterion("subjectTeacherName is not null");
			return this;
		}

		public Criteria andSubjectteachernameEqualTo(String value) {
			addCriterion("subjectTeacherName =", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameNotEqualTo(String value) {
			addCriterion("subjectTeacherName <>", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameGreaterThan(String value) {
			addCriterion("subjectTeacherName >", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameGreaterThanOrEqualTo(String value) {
			addCriterion("subjectTeacherName >=", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameLessThan(String value) {
			addCriterion("subjectTeacherName <", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameLessThanOrEqualTo(String value) {
			addCriterion("subjectTeacherName <=", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameLike(String value) {
			addCriterion("subjectTeacherName like", value, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameNotLike(String value) {
			addCriterion("subjectTeacherName not like", value,
					"subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameIn(List values) {
			addCriterion("subjectTeacherName in", values, "subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameNotIn(List values) {
			addCriterion("subjectTeacherName not in", values,
					"subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameBetween(String value1,
				String value2) {
			addCriterion("subjectTeacherName between", value1, value2,
					"subjectteachername");
			return this;
		}

		public Criteria andSubjectteachernameNotBetween(String value1,
				String value2) {
			addCriterion("subjectTeacherName not between", value1, value2,
					"subjectteachername");
			return this;
		}

		public Criteria andSubjectteacheridIsNull() {
			addCriterion("subjectTeacherId is null");
			return this;
		}

		public Criteria andSubjectteacheridIsNotNull() {
			addCriterion("subjectTeacherId is not null");
			return this;
		}

		public Criteria andSubjectteacheridEqualTo(Long value) {
			addCriterion("subjectTeacherId =", value, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridNotEqualTo(Long value) {
			addCriterion("subjectTeacherId <>", value, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridGreaterThan(Long value) {
			addCriterion("subjectTeacherId >", value, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridGreaterThanOrEqualTo(Long value) {
			addCriterion("subjectTeacherId >=", value, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridLessThan(Long value) {
			addCriterion("subjectTeacherId <", value, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridLessThanOrEqualTo(Long value) {
			addCriterion("subjectTeacherId <=", value, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridIn(List values) {
			addCriterion("subjectTeacherId in", values, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridNotIn(List values) {
			addCriterion("subjectTeacherId not in", values, "subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridBetween(Long value1, Long value2) {
			addCriterion("subjectTeacherId between", value1, value2,
					"subjectteacherid");
			return this;
		}

		public Criteria andSubjectteacheridNotBetween(Long value1, Long value2) {
			addCriterion("subjectTeacherId not between", value1, value2,
					"subjectteacherid");
			return this;
		}

		public Criteria andSubjectdepartmentIsNull() {
			addCriterion("subjectDepartment is null");
			return this;
		}

		public Criteria andSubjectdepartmentIsNotNull() {
			addCriterion("subjectDepartment is not null");
			return this;
		}

		public Criteria andSubjectdepartmentEqualTo(String value) {
			addCriterion("subjectDepartment =", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentNotEqualTo(String value) {
			addCriterion("subjectDepartment <>", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentGreaterThan(String value) {
			addCriterion("subjectDepartment >", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("subjectDepartment >=", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentLessThan(String value) {
			addCriterion("subjectDepartment <", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentLessThanOrEqualTo(String value) {
			addCriterion("subjectDepartment <=", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentLike(String value) {
			addCriterion("subjectDepartment like", value, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentNotLike(String value) {
			addCriterion("subjectDepartment not like", value,
					"subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentIn(List values) {
			addCriterion("subjectDepartment in", values, "subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentNotIn(List values) {
			addCriterion("subjectDepartment not in", values,
					"subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentBetween(String value1, String value2) {
			addCriterion("subjectDepartment between", value1, value2,
					"subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentNotBetween(String value1,
				String value2) {
			addCriterion("subjectDepartment not between", value1, value2,
					"subjectdepartment");
			return this;
		}

		public Criteria andSubjectdepartmentnameIsNull() {
			addCriterion("subjectDepartmentName is null");
			return this;
		}

		public Criteria andSubjectdepartmentnameIsNotNull() {
			addCriterion("subjectDepartmentName is not null");
			return this;
		}

		public Criteria andSubjectdepartmentnameEqualTo(String value) {
			addCriterion("subjectDepartmentName =", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameNotEqualTo(String value) {
			addCriterion("subjectDepartmentName <>", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameGreaterThan(String value) {
			addCriterion("subjectDepartmentName >", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameGreaterThanOrEqualTo(
				String value) {
			addCriterion("subjectDepartmentName >=", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameLessThan(String value) {
			addCriterion("subjectDepartmentName <", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameLessThanOrEqualTo(String value) {
			addCriterion("subjectDepartmentName <=", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameLike(String value) {
			addCriterion("subjectDepartmentName like", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameNotLike(String value) {
			addCriterion("subjectDepartmentName not like", value,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameIn(List values) {
			addCriterion("subjectDepartmentName in", values,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameNotIn(List values) {
			addCriterion("subjectDepartmentName not in", values,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameBetween(String value1,
				String value2) {
			addCriterion("subjectDepartmentName between", value1, value2,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectdepartmentnameNotBetween(String value1,
				String value2) {
			addCriterion("subjectDepartmentName not between", value1, value2,
					"subjectdepartmentname");
			return this;
		}

		public Criteria andSubjectyearIsNull() {
			addCriterion("subjectYear is null");
			return this;
		}

		public Criteria andSubjectyearIsNotNull() {
			addCriterion("subjectYear is not null");
			return this;
		}

		public Criteria andSubjectyearEqualTo(String value) {
			addCriterion("subjectYear =", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearNotEqualTo(String value) {
			addCriterion("subjectYear <>", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearGreaterThan(String value) {
			addCriterion("subjectYear >", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearGreaterThanOrEqualTo(String value) {
			addCriterion("subjectYear >=", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearLessThan(String value) {
			addCriterion("subjectYear <", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearLessThanOrEqualTo(String value) {
			addCriterion("subjectYear <=", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearLike(String value) {
			addCriterion("subjectYear like", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearNotLike(String value) {
			addCriterion("subjectYear not like", value, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearIn(List values) {
			addCriterion("subjectYear in", values, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearNotIn(List values) {
			addCriterion("subjectYear not in", values, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearBetween(String value1, String value2) {
			addCriterion("subjectYear between", value1, value2, "subjectyear");
			return this;
		}

		public Criteria andSubjectyearNotBetween(String value1, String value2) {
			addCriterion("subjectYear not between", value1, value2,
					"subjectyear");
			return this;
		}

		public Criteria andSubjectremarkIsNull() {
			addCriterion("subjectRemark is null");
			return this;
		}

		public Criteria andSubjectremarkIsNotNull() {
			addCriterion("subjectRemark is not null");
			return this;
		}

		public Criteria andSubjectremarkEqualTo(String value) {
			addCriterion("subjectRemark =", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkNotEqualTo(String value) {
			addCriterion("subjectRemark <>", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkGreaterThan(String value) {
			addCriterion("subjectRemark >", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkGreaterThanOrEqualTo(String value) {
			addCriterion("subjectRemark >=", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkLessThan(String value) {
			addCriterion("subjectRemark <", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkLessThanOrEqualTo(String value) {
			addCriterion("subjectRemark <=", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkLike(String value) {
			addCriterion("subjectRemark like", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkNotLike(String value) {
			addCriterion("subjectRemark not like", value, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkIn(List values) {
			addCriterion("subjectRemark in", values, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkNotIn(List values) {
			addCriterion("subjectRemark not in", values, "subjectremark");
			return this;
		}

		public Criteria andSubjectremarkBetween(String value1, String value2) {
			addCriterion("subjectRemark between", value1, value2,
					"subjectremark");
			return this;
		}

		public Criteria andSubjectremarkNotBetween(String value1, String value2) {
			addCriterion("subjectRemark not between", value1, value2,
					"subjectremark");
			return this;
		}

		public Criteria andSubjectcreditIsNull() {
			addCriterion("subjectCredit is null");
			return this;
		}

		public Criteria andSubjectcreditIsNotNull() {
			addCriterion("subjectCredit is not null");
			return this;
		}

		public Criteria andSubjectcreditEqualTo(String value) {
			addCriterion("subjectCredit =", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditNotEqualTo(String value) {
			addCriterion("subjectCredit <>", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditGreaterThan(String value) {
			addCriterion("subjectCredit >", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditGreaterThanOrEqualTo(String value) {
			addCriterion("subjectCredit >=", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditLessThan(String value) {
			addCriterion("subjectCredit <", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditLessThanOrEqualTo(String value) {
			addCriterion("subjectCredit <=", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditLike(String value) {
			addCriterion("subjectCredit like", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditNotLike(String value) {
			addCriterion("subjectCredit not like", value, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditIn(List values) {
			addCriterion("subjectCredit in", values, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditNotIn(List values) {
			addCriterion("subjectCredit not in", values, "subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditBetween(String value1, String value2) {
			addCriterion("subjectCredit between", value1, value2,
					"subjectcredit");
			return this;
		}

		public Criteria andSubjectcreditNotBetween(String value1, String value2) {
			addCriterion("subjectCredit not between", value1, value2,
					"subjectcredit");
			return this;
		}

		public Criteria andClasshourfortheoryIsNull() {
			addCriterion("classHourForTheory is null");
			return this;
		}

		public Criteria andClasshourfortheoryIsNotNull() {
			addCriterion("classHourForTheory is not null");
			return this;
		}

		public Criteria andClasshourfortheoryEqualTo(String value) {
			addCriterion("classHourForTheory =", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryNotEqualTo(String value) {
			addCriterion("classHourForTheory <>", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryGreaterThan(String value) {
			addCriterion("classHourForTheory >", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryGreaterThanOrEqualTo(String value) {
			addCriterion("classHourForTheory >=", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryLessThan(String value) {
			addCriterion("classHourForTheory <", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryLessThanOrEqualTo(String value) {
			addCriterion("classHourForTheory <=", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryLike(String value) {
			addCriterion("classHourForTheory like", value, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryNotLike(String value) {
			addCriterion("classHourForTheory not like", value,
					"classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryIn(List values) {
			addCriterion("classHourForTheory in", values, "classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryNotIn(List values) {
			addCriterion("classHourForTheory not in", values,
					"classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryBetween(String value1,
				String value2) {
			addCriterion("classHourForTheory between", value1, value2,
					"classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortheoryNotBetween(String value1,
				String value2) {
			addCriterion("classHourForTheory not between", value1, value2,
					"classhourfortheory");
			return this;
		}

		public Criteria andClasshourfortestIsNull() {
			addCriterion("classHourForTest is null");
			return this;
		}

		public Criteria andClasshourfortestIsNotNull() {
			addCriterion("classHourForTest is not null");
			return this;
		}

		public Criteria andClasshourfortestEqualTo(String value) {
			addCriterion("classHourForTest =", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestNotEqualTo(String value) {
			addCriterion("classHourForTest <>", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestGreaterThan(String value) {
			addCriterion("classHourForTest >", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestGreaterThanOrEqualTo(String value) {
			addCriterion("classHourForTest >=", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestLessThan(String value) {
			addCriterion("classHourForTest <", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestLessThanOrEqualTo(String value) {
			addCriterion("classHourForTest <=", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestLike(String value) {
			addCriterion("classHourForTest like", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestNotLike(String value) {
			addCriterion("classHourForTest not like", value, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestIn(List values) {
			addCriterion("classHourForTest in", values, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestNotIn(List values) {
			addCriterion("classHourForTest not in", values, "classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestBetween(String value1, String value2) {
			addCriterion("classHourForTest between", value1, value2,
					"classhourfortest");
			return this;
		}

		public Criteria andClasshourfortestNotBetween(String value1,
				String value2) {
			addCriterion("classHourForTest not between", value1, value2,
					"classhourfortest");
			return this;
		}

		public Criteria andClasshourformachineIsNull() {
			addCriterion("classHourForMachine is null");
			return this;
		}

		public Criteria andClasshourformachineIsNotNull() {
			addCriterion("classHourForMachine is not null");
			return this;
		}

		public Criteria andClasshourformachineEqualTo(String value) {
			addCriterion("classHourForMachine =", value, "classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineNotEqualTo(String value) {
			addCriterion("classHourForMachine <>", value, "classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineGreaterThan(String value) {
			addCriterion("classHourForMachine >", value, "classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineGreaterThanOrEqualTo(String value) {
			addCriterion("classHourForMachine >=", value, "classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineLessThan(String value) {
			addCriterion("classHourForMachine <", value, "classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineLessThanOrEqualTo(String value) {
			addCriterion("classHourForMachine <=", value, "classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineLike(String value) {
			addCriterion("classHourForMachine like", value,
					"classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineNotLike(String value) {
			addCriterion("classHourForMachine not like", value,
					"classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineIn(List values) {
			addCriterion("classHourForMachine in", values,
					"classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineNotIn(List values) {
			addCriterion("classHourForMachine not in", values,
					"classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineBetween(String value1,
				String value2) {
			addCriterion("classHourForMachine between", value1, value2,
					"classhourformachine");
			return this;
		}

		public Criteria andClasshourformachineNotBetween(String value1,
				String value2) {
			addCriterion("classHourForMachine not between", value1, value2,
					"classhourformachine");
			return this;
		}

		public Criteria andClasshourforotherIsNull() {
			addCriterion("classHourForOther is null");
			return this;
		}

		public Criteria andClasshourforotherIsNotNull() {
			addCriterion("classHourForOther is not null");
			return this;
		}

		public Criteria andClasshourforotherEqualTo(String value) {
			addCriterion("classHourForOther =", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherNotEqualTo(String value) {
			addCriterion("classHourForOther <>", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherGreaterThan(String value) {
			addCriterion("classHourForOther >", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherGreaterThanOrEqualTo(String value) {
			addCriterion("classHourForOther >=", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherLessThan(String value) {
			addCriterion("classHourForOther <", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherLessThanOrEqualTo(String value) {
			addCriterion("classHourForOther <=", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherLike(String value) {
			addCriterion("classHourForOther like", value, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherNotLike(String value) {
			addCriterion("classHourForOther not like", value,
					"classhourforother");
			return this;
		}

		public Criteria andClasshourforotherIn(List values) {
			addCriterion("classHourForOther in", values, "classhourforother");
			return this;
		}

		public Criteria andClasshourforotherNotIn(List values) {
			addCriterion("classHourForOther not in", values,
					"classhourforother");
			return this;
		}

		public Criteria andClasshourforotherBetween(String value1, String value2) {
			addCriterion("classHourForOther between", value1, value2,
					"classhourforother");
			return this;
		}

		public Criteria andClasshourforotherNotBetween(String value1,
				String value2) {
			addCriterion("classHourForOther not between", value1, value2,
					"classhourforother");
			return this;
		}

		public Criteria andTermclasshourforoneIsNull() {
			addCriterion("termClassHourForOne is null");
			return this;
		}

		public Criteria andTermclasshourforoneIsNotNull() {
			addCriterion("termClassHourForOne is not null");
			return this;
		}

		public Criteria andTermclasshourforoneEqualTo(String value) {
			addCriterion("termClassHourForOne =", value, "termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneNotEqualTo(String value) {
			addCriterion("termClassHourForOne <>", value, "termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneGreaterThan(String value) {
			addCriterion("termClassHourForOne >", value, "termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneGreaterThanOrEqualTo(String value) {
			addCriterion("termClassHourForOne >=", value, "termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneLessThan(String value) {
			addCriterion("termClassHourForOne <", value, "termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForOne <=", value, "termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneLike(String value) {
			addCriterion("termClassHourForOne like", value,
					"termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneNotLike(String value) {
			addCriterion("termClassHourForOne not like", value,
					"termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneIn(List values) {
			addCriterion("termClassHourForOne in", values,
					"termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneNotIn(List values) {
			addCriterion("termClassHourForOne not in", values,
					"termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneBetween(String value1,
				String value2) {
			addCriterion("termClassHourForOne between", value1, value2,
					"termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourforoneNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForOne not between", value1, value2,
					"termclasshourforone");
			return this;
		}

		public Criteria andTermclasshourfortwoIsNull() {
			addCriterion("termClassHourForTwo is null");
			return this;
		}

		public Criteria andTermclasshourfortwoIsNotNull() {
			addCriterion("termClassHourForTwo is not null");
			return this;
		}

		public Criteria andTermclasshourfortwoEqualTo(String value) {
			addCriterion("termClassHourForTwo =", value, "termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoNotEqualTo(String value) {
			addCriterion("termClassHourForTwo <>", value, "termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoGreaterThan(String value) {
			addCriterion("termClassHourForTwo >", value, "termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoGreaterThanOrEqualTo(String value) {
			addCriterion("termClassHourForTwo >=", value, "termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoLessThan(String value) {
			addCriterion("termClassHourForTwo <", value, "termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForTwo <=", value, "termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoLike(String value) {
			addCriterion("termClassHourForTwo like", value,
					"termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoNotLike(String value) {
			addCriterion("termClassHourForTwo not like", value,
					"termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoIn(List values) {
			addCriterion("termClassHourForTwo in", values,
					"termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoNotIn(List values) {
			addCriterion("termClassHourForTwo not in", values,
					"termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoBetween(String value1,
				String value2) {
			addCriterion("termClassHourForTwo between", value1, value2,
					"termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourfortwoNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForTwo not between", value1, value2,
					"termclasshourfortwo");
			return this;
		}

		public Criteria andTermclasshourforthreeIsNull() {
			addCriterion("termClassHourForThree is null");
			return this;
		}

		public Criteria andTermclasshourforthreeIsNotNull() {
			addCriterion("termClassHourForThree is not null");
			return this;
		}

		public Criteria andTermclasshourforthreeEqualTo(String value) {
			addCriterion("termClassHourForThree =", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeNotEqualTo(String value) {
			addCriterion("termClassHourForThree <>", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeGreaterThan(String value) {
			addCriterion("termClassHourForThree >", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeGreaterThanOrEqualTo(
				String value) {
			addCriterion("termClassHourForThree >=", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeLessThan(String value) {
			addCriterion("termClassHourForThree <", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForThree <=", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeLike(String value) {
			addCriterion("termClassHourForThree like", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeNotLike(String value) {
			addCriterion("termClassHourForThree not like", value,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeIn(List values) {
			addCriterion("termClassHourForThree in", values,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeNotIn(List values) {
			addCriterion("termClassHourForThree not in", values,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeBetween(String value1,
				String value2) {
			addCriterion("termClassHourForThree between", value1, value2,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforthreeNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForThree not between", value1, value2,
					"termclasshourforthree");
			return this;
		}

		public Criteria andTermclasshourforfourIsNull() {
			addCriterion("termClassHourForFour is null");
			return this;
		}

		public Criteria andTermclasshourforfourIsNotNull() {
			addCriterion("termClassHourForFour is not null");
			return this;
		}

		public Criteria andTermclasshourforfourEqualTo(String value) {
			addCriterion("termClassHourForFour =", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourNotEqualTo(String value) {
			addCriterion("termClassHourForFour <>", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourGreaterThan(String value) {
			addCriterion("termClassHourForFour >", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourGreaterThanOrEqualTo(String value) {
			addCriterion("termClassHourForFour >=", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourLessThan(String value) {
			addCriterion("termClassHourForFour <", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForFour <=", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourLike(String value) {
			addCriterion("termClassHourForFour like", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourNotLike(String value) {
			addCriterion("termClassHourForFour not like", value,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourIn(List values) {
			addCriterion("termClassHourForFour in", values,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourNotIn(List values) {
			addCriterion("termClassHourForFour not in", values,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourBetween(String value1,
				String value2) {
			addCriterion("termClassHourForFour between", value1, value2,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfourNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForFour not between", value1, value2,
					"termclasshourforfour");
			return this;
		}

		public Criteria andTermclasshourforfiveIsNull() {
			addCriterion("termClassHourForFive is null");
			return this;
		}

		public Criteria andTermclasshourforfiveIsNotNull() {
			addCriterion("termClassHourForFive is not null");
			return this;
		}

		public Criteria andTermclasshourforfiveEqualTo(String value) {
			addCriterion("termClassHourForFive =", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveNotEqualTo(String value) {
			addCriterion("termClassHourForFive <>", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveGreaterThan(String value) {
			addCriterion("termClassHourForFive >", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveGreaterThanOrEqualTo(String value) {
			addCriterion("termClassHourForFive >=", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveLessThan(String value) {
			addCriterion("termClassHourForFive <", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForFive <=", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveLike(String value) {
			addCriterion("termClassHourForFive like", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveNotLike(String value) {
			addCriterion("termClassHourForFive not like", value,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveIn(List values) {
			addCriterion("termClassHourForFive in", values,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveNotIn(List values) {
			addCriterion("termClassHourForFive not in", values,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveBetween(String value1,
				String value2) {
			addCriterion("termClassHourForFive between", value1, value2,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforfiveNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForFive not between", value1, value2,
					"termclasshourforfive");
			return this;
		}

		public Criteria andTermclasshourforsixIsNull() {
			addCriterion("termClassHourForSix is null");
			return this;
		}

		public Criteria andTermclasshourforsixIsNotNull() {
			addCriterion("termClassHourForSix is not null");
			return this;
		}

		public Criteria andTermclasshourforsixEqualTo(String value) {
			addCriterion("termClassHourForSix =", value, "termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixNotEqualTo(String value) {
			addCriterion("termClassHourForSix <>", value, "termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixGreaterThan(String value) {
			addCriterion("termClassHourForSix >", value, "termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixGreaterThanOrEqualTo(String value) {
			addCriterion("termClassHourForSix >=", value, "termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixLessThan(String value) {
			addCriterion("termClassHourForSix <", value, "termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForSix <=", value, "termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixLike(String value) {
			addCriterion("termClassHourForSix like", value,
					"termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixNotLike(String value) {
			addCriterion("termClassHourForSix not like", value,
					"termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixIn(List values) {
			addCriterion("termClassHourForSix in", values,
					"termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixNotIn(List values) {
			addCriterion("termClassHourForSix not in", values,
					"termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixBetween(String value1,
				String value2) {
			addCriterion("termClassHourForSix between", value1, value2,
					"termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsixNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForSix not between", value1, value2,
					"termclasshourforsix");
			return this;
		}

		public Criteria andTermclasshourforsevenIsNull() {
			addCriterion("termClassHourForSeven is null");
			return this;
		}

		public Criteria andTermclasshourforsevenIsNotNull() {
			addCriterion("termClassHourForSeven is not null");
			return this;
		}

		public Criteria andTermclasshourforsevenEqualTo(String value) {
			addCriterion("termClassHourForSeven =", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenNotEqualTo(String value) {
			addCriterion("termClassHourForSeven <>", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenGreaterThan(String value) {
			addCriterion("termClassHourForSeven >", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenGreaterThanOrEqualTo(
				String value) {
			addCriterion("termClassHourForSeven >=", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenLessThan(String value) {
			addCriterion("termClassHourForSeven <", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForSeven <=", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenLike(String value) {
			addCriterion("termClassHourForSeven like", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenNotLike(String value) {
			addCriterion("termClassHourForSeven not like", value,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenIn(List values) {
			addCriterion("termClassHourForSeven in", values,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenNotIn(List values) {
			addCriterion("termClassHourForSeven not in", values,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenBetween(String value1,
				String value2) {
			addCriterion("termClassHourForSeven between", value1, value2,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforsevenNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForSeven not between", value1, value2,
					"termclasshourforseven");
			return this;
		}

		public Criteria andTermclasshourforeightIsNull() {
			addCriterion("termClassHourForEight is null");
			return this;
		}

		public Criteria andTermclasshourforeightIsNotNull() {
			addCriterion("termClassHourForEight is not null");
			return this;
		}

		public Criteria andTermclasshourforeightEqualTo(String value) {
			addCriterion("termClassHourForEight =", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightNotEqualTo(String value) {
			addCriterion("termClassHourForEight <>", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightGreaterThan(String value) {
			addCriterion("termClassHourForEight >", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightGreaterThanOrEqualTo(
				String value) {
			addCriterion("termClassHourForEight >=", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightLessThan(String value) {
			addCriterion("termClassHourForEight <", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightLessThanOrEqualTo(String value) {
			addCriterion("termClassHourForEight <=", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightLike(String value) {
			addCriterion("termClassHourForEight like", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightNotLike(String value) {
			addCriterion("termClassHourForEight not like", value,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightIn(List values) {
			addCriterion("termClassHourForEight in", values,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightNotIn(List values) {
			addCriterion("termClassHourForEight not in", values,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightBetween(String value1,
				String value2) {
			addCriterion("termClassHourForEight between", value1, value2,
					"termclasshourforeight");
			return this;
		}

		public Criteria andTermclasshourforeightNotBetween(String value1,
				String value2) {
			addCriterion("termClassHourForEight not between", value1, value2,
					"termclasshourforeight");
			return this;
		}
	}
}