package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TSubjectExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public TSubjectExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	protected TSubjectExample(TSubjectExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_subject
	 * @ibatorgenerated  Wed Jan 07 10:28:51 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andSubjectnameIsNull() {
			addCriterion("subjectname is null");
			return this;
		}

		public Criteria andSubjectnameIsNotNull() {
			addCriterion("subjectname is not null");
			return this;
		}

		public Criteria andSubjectnameEqualTo(String value) {
			addCriterion("subjectname =", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotEqualTo(String value) {
			addCriterion("subjectname <>", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameGreaterThan(String value) {
			addCriterion("subjectname >", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameGreaterThanOrEqualTo(String value) {
			addCriterion("subjectname >=", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameLessThan(String value) {
			addCriterion("subjectname <", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameLessThanOrEqualTo(String value) {
			addCriterion("subjectname <=", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameLike(String value) {
			addCriterion("subjectname like", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotLike(String value) {
			addCriterion("subjectname not like", value, "subjectname");
			return this;
		}

		public Criteria andSubjectnameIn(List values) {
			addCriterion("subjectname in", values, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotIn(List values) {
			addCriterion("subjectname not in", values, "subjectname");
			return this;
		}

		public Criteria andSubjectnameBetween(String value1, String value2) {
			addCriterion("subjectname between", value1, value2, "subjectname");
			return this;
		}

		public Criteria andSubjectnameNotBetween(String value1, String value2) {
			addCriterion("subjectname not between", value1, value2,
					"subjectname");
			return this;
		}

		public Criteria andSubjecttextIsNull() {
			addCriterion("subjecttext is null");
			return this;
		}

		public Criteria andSubjecttextIsNotNull() {
			addCriterion("subjecttext is not null");
			return this;
		}

		public Criteria andSubjecttextEqualTo(String value) {
			addCriterion("subjecttext =", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotEqualTo(String value) {
			addCriterion("subjecttext <>", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextGreaterThan(String value) {
			addCriterion("subjecttext >", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextGreaterThanOrEqualTo(String value) {
			addCriterion("subjecttext >=", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextLessThan(String value) {
			addCriterion("subjecttext <", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextLessThanOrEqualTo(String value) {
			addCriterion("subjecttext <=", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextLike(String value) {
			addCriterion("subjecttext like", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotLike(String value) {
			addCriterion("subjecttext not like", value, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextIn(List values) {
			addCriterion("subjecttext in", values, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotIn(List values) {
			addCriterion("subjecttext not in", values, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextBetween(String value1, String value2) {
			addCriterion("subjecttext between", value1, value2, "subjecttext");
			return this;
		}

		public Criteria andSubjecttextNotBetween(String value1, String value2) {
			addCriterion("subjecttext not between", value1, value2,
					"subjecttext");
			return this;
		}

		public Criteria andSubjecttypeIsNull() {
			addCriterion("subjecttype is null");
			return this;
		}

		public Criteria andSubjecttypeIsNotNull() {
			addCriterion("subjecttype is not null");
			return this;
		}

		public Criteria andSubjecttypeEqualTo(Integer value) {
			addCriterion("subjecttype =", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotEqualTo(Integer value) {
			addCriterion("subjecttype <>", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeGreaterThan(Integer value) {
			addCriterion("subjecttype >", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("subjecttype >=", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeLessThan(Integer value) {
			addCriterion("subjecttype <", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeLessThanOrEqualTo(Integer value) {
			addCriterion("subjecttype <=", value, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeIn(List values) {
			addCriterion("subjecttype in", values, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotIn(List values) {
			addCriterion("subjecttype not in", values, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeBetween(Integer value1, Integer value2) {
			addCriterion("subjecttype between", value1, value2, "subjecttype");
			return this;
		}

		public Criteria andSubjecttypeNotBetween(Integer value1, Integer value2) {
			addCriterion("subjecttype not between", value1, value2,
					"subjecttype");
			return this;
		}

		public Criteria andSubjecttypenameIsNull() {
			addCriterion("subjecttypename is null");
			return this;
		}

		public Criteria andSubjecttypenameIsNotNull() {
			addCriterion("subjecttypename is not null");
			return this;
		}

		public Criteria andSubjecttypenameEqualTo(String value) {
			addCriterion("subjecttypename =", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotEqualTo(String value) {
			addCriterion("subjecttypename <>", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameGreaterThan(String value) {
			addCriterion("subjecttypename >", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameGreaterThanOrEqualTo(String value) {
			addCriterion("subjecttypename >=", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameLessThan(String value) {
			addCriterion("subjecttypename <", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameLessThanOrEqualTo(String value) {
			addCriterion("subjecttypename <=", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameLike(String value) {
			addCriterion("subjecttypename like", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotLike(String value) {
			addCriterion("subjecttypename not like", value, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameIn(List values) {
			addCriterion("subjecttypename in", values, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotIn(List values) {
			addCriterion("subjecttypename not in", values, "subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameBetween(String value1, String value2) {
			addCriterion("subjecttypename between", value1, value2,
					"subjecttypename");
			return this;
		}

		public Criteria andSubjecttypenameNotBetween(String value1,
				String value2) {
			addCriterion("subjecttypename not between", value1, value2,
					"subjecttypename");
			return this;
		}

		public Criteria andSubjectisvalidIsNull() {
			addCriterion("subjectisvalid is null");
			return this;
		}

		public Criteria andSubjectisvalidIsNotNull() {
			addCriterion("subjectisvalid is not null");
			return this;
		}

		public Criteria andSubjectisvalidEqualTo(String value) {
			addCriterion("subjectisvalid =", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotEqualTo(String value) {
			addCriterion("subjectisvalid <>", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidGreaterThan(String value) {
			addCriterion("subjectisvalid >", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidGreaterThanOrEqualTo(String value) {
			addCriterion("subjectisvalid >=", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidLessThan(String value) {
			addCriterion("subjectisvalid <", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidLessThanOrEqualTo(String value) {
			addCriterion("subjectisvalid <=", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidLike(String value) {
			addCriterion("subjectisvalid like", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotLike(String value) {
			addCriterion("subjectisvalid not like", value, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidIn(List values) {
			addCriterion("subjectisvalid in", values, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotIn(List values) {
			addCriterion("subjectisvalid not in", values, "subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidBetween(String value1, String value2) {
			addCriterion("subjectisvalid between", value1, value2,
					"subjectisvalid");
			return this;
		}

		public Criteria andSubjectisvalidNotBetween(String value1, String value2) {
			addCriterion("subjectisvalid not between", value1, value2,
					"subjectisvalid");
			return this;
		}
	}
}