package com.et59.cus.domain.entity;

public class TTrainingplan {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_trainingplan.trainingPlanId
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    private Long trainingplanid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_trainingplan.trainingPlanSubjectName
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    private String trainingplansubjectname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_trainingplan.trainingPlanSubjectId
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    private Long trainingplansubjectid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_trainingplan.trainingPlanSubjectText
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    private String trainingplansubjecttext;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_trainingplan.trainingPlanId
     *
     * @return the value of t_trainingplan.trainingPlanId
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public Long getTrainingplanid() {
        return trainingplanid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_trainingplan.trainingPlanId
     *
     * @param trainingplanid the value for t_trainingplan.trainingPlanId
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public void setTrainingplanid(Long trainingplanid) {
        this.trainingplanid = trainingplanid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_trainingplan.trainingPlanSubjectName
     *
     * @return the value of t_trainingplan.trainingPlanSubjectName
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public String getTrainingplansubjectname() {
        return trainingplansubjectname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_trainingplan.trainingPlanSubjectName
     *
     * @param trainingplansubjectname the value for t_trainingplan.trainingPlanSubjectName
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public void setTrainingplansubjectname(String trainingplansubjectname) {
        this.trainingplansubjectname = trainingplansubjectname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_trainingplan.trainingPlanSubjectId
     *
     * @return the value of t_trainingplan.trainingPlanSubjectId
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public Long getTrainingplansubjectid() {
        return trainingplansubjectid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_trainingplan.trainingPlanSubjectId
     *
     * @param trainingplansubjectid the value for t_trainingplan.trainingPlanSubjectId
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public void setTrainingplansubjectid(Long trainingplansubjectid) {
        this.trainingplansubjectid = trainingplansubjectid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_trainingplan.trainingPlanSubjectText
     *
     * @return the value of t_trainingplan.trainingPlanSubjectText
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public String getTrainingplansubjecttext() {
        return trainingplansubjecttext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_trainingplan.trainingPlanSubjectText
     *
     * @param trainingplansubjecttext the value for t_trainingplan.trainingPlanSubjectText
     *
     * @ibatorgenerated Tue Mar 24 14:56:05 CST 2015
     */
    public void setTrainingplansubjecttext(String trainingplansubjecttext) {
        this.trainingplansubjecttext = trainingplansubjecttext;
    }
}