package com.et59.cus.domain.entity;

public class TVisitschool {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitId
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private Long visitid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitName
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private String visitname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitBegDate
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private String visitbegdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitEndDate
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private String visitenddate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitLength
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private String visitlength;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitPlace
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private String visitplace;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.visitForProject
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private String visitforproject;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_visitschool.teacherId
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private Long teacherid;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitId
	 * @return  the value of t_visitschool.visitId
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public Long getVisitid() {
		return visitid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitId
	 * @param visitid  the value for t_visitschool.visitId
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitid(Long visitid) {
		this.visitid = visitid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitName
	 * @return  the value of t_visitschool.visitName
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public String getVisitname() {
		return visitname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitName
	 * @param visitname  the value for t_visitschool.visitName
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitname(String visitname) {
		this.visitname = visitname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitBegDate
	 * @return  the value of t_visitschool.visitBegDate
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public String getVisitbegdate() {
		return visitbegdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitBegDate
	 * @param visitbegdate  the value for t_visitschool.visitBegDate
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitbegdate(String visitbegdate) {
		this.visitbegdate = visitbegdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitEndDate
	 * @return  the value of t_visitschool.visitEndDate
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public String getVisitenddate() {
		return visitenddate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitEndDate
	 * @param visitenddate  the value for t_visitschool.visitEndDate
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitenddate(String visitenddate) {
		this.visitenddate = visitenddate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitLength
	 * @return  the value of t_visitschool.visitLength
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public String getVisitlength() {
		return visitlength;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitLength
	 * @param visitlength  the value for t_visitschool.visitLength
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitlength(String visitlength) {
		this.visitlength = visitlength;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitPlace
	 * @return  the value of t_visitschool.visitPlace
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public String getVisitplace() {
		return visitplace;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitPlace
	 * @param visitplace  the value for t_visitschool.visitPlace
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitplace(String visitplace) {
		this.visitplace = visitplace;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.visitForProject
	 * @return  the value of t_visitschool.visitForProject
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public String getVisitforproject() {
		return visitforproject;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.visitForProject
	 * @param visitforproject  the value for t_visitschool.visitForProject
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setVisitforproject(String visitforproject) {
		this.visitforproject = visitforproject;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_visitschool.teacherId
	 * @return  the value of t_visitschool.teacherId
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public Long getTeacherid() {
		return teacherid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_visitschool.teacherId
	 * @param teacherid  the value for t_visitschool.teacherId
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void setTeacherid(Long teacherid) {
		this.teacherid = teacherid;
	}
}