package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TWorkExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public TWorkExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	protected TWorkExample(TWorkExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_work
	 * @ibatorgenerated  Sun May 24 18:20:27 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andWorkidIsNull() {
			addCriterion("workId is null");
			return this;
		}

		public Criteria andWorkidIsNotNull() {
			addCriterion("workId is not null");
			return this;
		}

		public Criteria andWorkidEqualTo(Long value) {
			addCriterion("workId =", value, "workid");
			return this;
		}

		public Criteria andWorkidNotEqualTo(Long value) {
			addCriterion("workId <>", value, "workid");
			return this;
		}

		public Criteria andWorkidGreaterThan(Long value) {
			addCriterion("workId >", value, "workid");
			return this;
		}

		public Criteria andWorkidGreaterThanOrEqualTo(Long value) {
			addCriterion("workId >=", value, "workid");
			return this;
		}

		public Criteria andWorkidLessThan(Long value) {
			addCriterion("workId <", value, "workid");
			return this;
		}

		public Criteria andWorkidLessThanOrEqualTo(Long value) {
			addCriterion("workId <=", value, "workid");
			return this;
		}

		public Criteria andWorkidIn(List values) {
			addCriterion("workId in", values, "workid");
			return this;
		}

		public Criteria andWorkidNotIn(List values) {
			addCriterion("workId not in", values, "workid");
			return this;
		}

		public Criteria andWorkidBetween(Long value1, Long value2) {
			addCriterion("workId between", value1, value2, "workid");
			return this;
		}

		public Criteria andWorkidNotBetween(Long value1, Long value2) {
			addCriterion("workId not between", value1, value2, "workid");
			return this;
		}

		public Criteria andWorkauthorrankIsNull() {
			addCriterion("workAuthorRank is null");
			return this;
		}

		public Criteria andWorkauthorrankIsNotNull() {
			addCriterion("workAuthorRank is not null");
			return this;
		}

		public Criteria andWorkauthorrankEqualTo(String value) {
			addCriterion("workAuthorRank =", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankNotEqualTo(String value) {
			addCriterion("workAuthorRank <>", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankGreaterThan(String value) {
			addCriterion("workAuthorRank >", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankGreaterThanOrEqualTo(String value) {
			addCriterion("workAuthorRank >=", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankLessThan(String value) {
			addCriterion("workAuthorRank <", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankLessThanOrEqualTo(String value) {
			addCriterion("workAuthorRank <=", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankLike(String value) {
			addCriterion("workAuthorRank like", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankNotLike(String value) {
			addCriterion("workAuthorRank not like", value, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankIn(List values) {
			addCriterion("workAuthorRank in", values, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankNotIn(List values) {
			addCriterion("workAuthorRank not in", values, "workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankBetween(String value1, String value2) {
			addCriterion("workAuthorRank between", value1, value2,
					"workauthorrank");
			return this;
		}

		public Criteria andWorkauthorrankNotBetween(String value1, String value2) {
			addCriterion("workAuthorRank not between", value1, value2,
					"workauthorrank");
			return this;
		}

		public Criteria andWorktitleIsNull() {
			addCriterion("workTitle is null");
			return this;
		}

		public Criteria andWorktitleIsNotNull() {
			addCriterion("workTitle is not null");
			return this;
		}

		public Criteria andWorktitleEqualTo(String value) {
			addCriterion("workTitle =", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleNotEqualTo(String value) {
			addCriterion("workTitle <>", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleGreaterThan(String value) {
			addCriterion("workTitle >", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleGreaterThanOrEqualTo(String value) {
			addCriterion("workTitle >=", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleLessThan(String value) {
			addCriterion("workTitle <", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleLessThanOrEqualTo(String value) {
			addCriterion("workTitle <=", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleLike(String value) {
			addCriterion("workTitle like", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleNotLike(String value) {
			addCriterion("workTitle not like", value, "worktitle");
			return this;
		}

		public Criteria andWorktitleIn(List values) {
			addCriterion("workTitle in", values, "worktitle");
			return this;
		}

		public Criteria andWorktitleNotIn(List values) {
			addCriterion("workTitle not in", values, "worktitle");
			return this;
		}

		public Criteria andWorktitleBetween(String value1, String value2) {
			addCriterion("workTitle between", value1, value2, "worktitle");
			return this;
		}

		public Criteria andWorktitleNotBetween(String value1, String value2) {
			addCriterion("workTitle not between", value1, value2, "worktitle");
			return this;
		}

		public Criteria andWorkpublishunitIsNull() {
			addCriterion("workPublishUnit is null");
			return this;
		}

		public Criteria andWorkpublishunitIsNotNull() {
			addCriterion("workPublishUnit is not null");
			return this;
		}

		public Criteria andWorkpublishunitEqualTo(String value) {
			addCriterion("workPublishUnit =", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitNotEqualTo(String value) {
			addCriterion("workPublishUnit <>", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitGreaterThan(String value) {
			addCriterion("workPublishUnit >", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitGreaterThanOrEqualTo(String value) {
			addCriterion("workPublishUnit >=", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitLessThan(String value) {
			addCriterion("workPublishUnit <", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitLessThanOrEqualTo(String value) {
			addCriterion("workPublishUnit <=", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitLike(String value) {
			addCriterion("workPublishUnit like", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitNotLike(String value) {
			addCriterion("workPublishUnit not like", value, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitIn(List values) {
			addCriterion("workPublishUnit in", values, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitNotIn(List values) {
			addCriterion("workPublishUnit not in", values, "workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitBetween(String value1, String value2) {
			addCriterion("workPublishUnit between", value1, value2,
					"workpublishunit");
			return this;
		}

		public Criteria andWorkpublishunitNotBetween(String value1,
				String value2) {
			addCriterion("workPublishUnit not between", value1, value2,
					"workpublishunit");
			return this;
		}

		public Criteria andWorktypeIsNull() {
			addCriterion("workType is null");
			return this;
		}

		public Criteria andWorktypeIsNotNull() {
			addCriterion("workType is not null");
			return this;
		}

		public Criteria andWorktypeEqualTo(String value) {
			addCriterion("workType =", value, "worktype");
			return this;
		}

		public Criteria andWorktypeNotEqualTo(String value) {
			addCriterion("workType <>", value, "worktype");
			return this;
		}

		public Criteria andWorktypeGreaterThan(String value) {
			addCriterion("workType >", value, "worktype");
			return this;
		}

		public Criteria andWorktypeGreaterThanOrEqualTo(String value) {
			addCriterion("workType >=", value, "worktype");
			return this;
		}

		public Criteria andWorktypeLessThan(String value) {
			addCriterion("workType <", value, "worktype");
			return this;
		}

		public Criteria andWorktypeLessThanOrEqualTo(String value) {
			addCriterion("workType <=", value, "worktype");
			return this;
		}

		public Criteria andWorktypeLike(String value) {
			addCriterion("workType like", value, "worktype");
			return this;
		}

		public Criteria andWorktypeNotLike(String value) {
			addCriterion("workType not like", value, "worktype");
			return this;
		}

		public Criteria andWorktypeIn(List values) {
			addCriterion("workType in", values, "worktype");
			return this;
		}

		public Criteria andWorktypeNotIn(List values) {
			addCriterion("workType not in", values, "worktype");
			return this;
		}

		public Criteria andWorktypeBetween(String value1, String value2) {
			addCriterion("workType between", value1, value2, "worktype");
			return this;
		}

		public Criteria andWorktypeNotBetween(String value1, String value2) {
			addCriterion("workType not between", value1, value2, "worktype");
			return this;
		}

		public Criteria andWorkpublishareaIsNull() {
			addCriterion("workPublishArea is null");
			return this;
		}

		public Criteria andWorkpublishareaIsNotNull() {
			addCriterion("workPublishArea is not null");
			return this;
		}

		public Criteria andWorkpublishareaEqualTo(String value) {
			addCriterion("workPublishArea =", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaNotEqualTo(String value) {
			addCriterion("workPublishArea <>", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaGreaterThan(String value) {
			addCriterion("workPublishArea >", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaGreaterThanOrEqualTo(String value) {
			addCriterion("workPublishArea >=", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaLessThan(String value) {
			addCriterion("workPublishArea <", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaLessThanOrEqualTo(String value) {
			addCriterion("workPublishArea <=", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaLike(String value) {
			addCriterion("workPublishArea like", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaNotLike(String value) {
			addCriterion("workPublishArea not like", value, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaIn(List values) {
			addCriterion("workPublishArea in", values, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaNotIn(List values) {
			addCriterion("workPublishArea not in", values, "workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaBetween(String value1, String value2) {
			addCriterion("workPublishArea between", value1, value2,
					"workpublisharea");
			return this;
		}

		public Criteria andWorkpublishareaNotBetween(String value1,
				String value2) {
			addCriterion("workPublishArea not between", value1, value2,
					"workpublisharea");
			return this;
		}

		public Criteria andWorkpublishtimeIsNull() {
			addCriterion("workPublishTime is null");
			return this;
		}

		public Criteria andWorkpublishtimeIsNotNull() {
			addCriterion("workPublishTime is not null");
			return this;
		}

		public Criteria andWorkpublishtimeEqualTo(String value) {
			addCriterion("workPublishTime =", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeNotEqualTo(String value) {
			addCriterion("workPublishTime <>", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeGreaterThan(String value) {
			addCriterion("workPublishTime >", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeGreaterThanOrEqualTo(String value) {
			addCriterion("workPublishTime >=", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeLessThan(String value) {
			addCriterion("workPublishTime <", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeLessThanOrEqualTo(String value) {
			addCriterion("workPublishTime <=", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeLike(String value) {
			addCriterion("workPublishTime like", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeNotLike(String value) {
			addCriterion("workPublishTime not like", value, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeIn(List values) {
			addCriterion("workPublishTime in", values, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeNotIn(List values) {
			addCriterion("workPublishTime not in", values, "workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeBetween(String value1, String value2) {
			addCriterion("workPublishTime between", value1, value2,
					"workpublishtime");
			return this;
		}

		public Criteria andWorkpublishtimeNotBetween(String value1,
				String value2) {
			addCriterion("workPublishTime not between", value1, value2,
					"workpublishtime");
			return this;
		}

		public Criteria andOriauthorIsNull() {
			addCriterion("oriAuthor is null");
			return this;
		}

		public Criteria andOriauthorIsNotNull() {
			addCriterion("oriAuthor is not null");
			return this;
		}

		public Criteria andOriauthorEqualTo(String value) {
			addCriterion("oriAuthor =", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorNotEqualTo(String value) {
			addCriterion("oriAuthor <>", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorGreaterThan(String value) {
			addCriterion("oriAuthor >", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorGreaterThanOrEqualTo(String value) {
			addCriterion("oriAuthor >=", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorLessThan(String value) {
			addCriterion("oriAuthor <", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorLessThanOrEqualTo(String value) {
			addCriterion("oriAuthor <=", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorLike(String value) {
			addCriterion("oriAuthor like", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorNotLike(String value) {
			addCriterion("oriAuthor not like", value, "oriauthor");
			return this;
		}

		public Criteria andOriauthorIn(List values) {
			addCriterion("oriAuthor in", values, "oriauthor");
			return this;
		}

		public Criteria andOriauthorNotIn(List values) {
			addCriterion("oriAuthor not in", values, "oriauthor");
			return this;
		}

		public Criteria andOriauthorBetween(String value1, String value2) {
			addCriterion("oriAuthor between", value1, value2, "oriauthor");
			return this;
		}

		public Criteria andOriauthorNotBetween(String value1, String value2) {
			addCriterion("oriAuthor not between", value1, value2, "oriauthor");
			return this;
		}

		public Criteria andTranslateforeignIsNull() {
			addCriterion("translateForeign is null");
			return this;
		}

		public Criteria andTranslateforeignIsNotNull() {
			addCriterion("translateForeign is not null");
			return this;
		}

		public Criteria andTranslateforeignEqualTo(String value) {
			addCriterion("translateForeign =", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignNotEqualTo(String value) {
			addCriterion("translateForeign <>", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignGreaterThan(String value) {
			addCriterion("translateForeign >", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignGreaterThanOrEqualTo(String value) {
			addCriterion("translateForeign >=", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignLessThan(String value) {
			addCriterion("translateForeign <", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignLessThanOrEqualTo(String value) {
			addCriterion("translateForeign <=", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignLike(String value) {
			addCriterion("translateForeign like", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignNotLike(String value) {
			addCriterion("translateForeign not like", value, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignIn(List values) {
			addCriterion("translateForeign in", values, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignNotIn(List values) {
			addCriterion("translateForeign not in", values, "translateforeign");
			return this;
		}

		public Criteria andTranslateforeignBetween(String value1, String value2) {
			addCriterion("translateForeign between", value1, value2,
					"translateforeign");
			return this;
		}

		public Criteria andTranslateforeignNotBetween(String value1,
				String value2) {
			addCriterion("translateForeign not between", value1, value2,
					"translateforeign");
			return this;
		}

		public Criteria andAlreadypublishIsNull() {
			addCriterion("alreadyPublish is null");
			return this;
		}

		public Criteria andAlreadypublishIsNotNull() {
			addCriterion("alreadyPublish is not null");
			return this;
		}

		public Criteria andAlreadypublishEqualTo(String value) {
			addCriterion("alreadyPublish =", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishNotEqualTo(String value) {
			addCriterion("alreadyPublish <>", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishGreaterThan(String value) {
			addCriterion("alreadyPublish >", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishGreaterThanOrEqualTo(String value) {
			addCriterion("alreadyPublish >=", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishLessThan(String value) {
			addCriterion("alreadyPublish <", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishLessThanOrEqualTo(String value) {
			addCriterion("alreadyPublish <=", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishLike(String value) {
			addCriterion("alreadyPublish like", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishNotLike(String value) {
			addCriterion("alreadyPublish not like", value, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishIn(List values) {
			addCriterion("alreadyPublish in", values, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishNotIn(List values) {
			addCriterion("alreadyPublish not in", values, "alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishBetween(String value1, String value2) {
			addCriterion("alreadyPublish between", value1, value2,
					"alreadypublish");
			return this;
		}

		public Criteria andAlreadypublishNotBetween(String value1, String value2) {
			addCriterion("alreadyPublish not between", value1, value2,
					"alreadypublish");
			return this;
		}

		public Criteria andIsbnnoIsNull() {
			addCriterion("isbnNO is null");
			return this;
		}

		public Criteria andIsbnnoIsNotNull() {
			addCriterion("isbnNO is not null");
			return this;
		}

		public Criteria andIsbnnoEqualTo(String value) {
			addCriterion("isbnNO =", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoNotEqualTo(String value) {
			addCriterion("isbnNO <>", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoGreaterThan(String value) {
			addCriterion("isbnNO >", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoGreaterThanOrEqualTo(String value) {
			addCriterion("isbnNO >=", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoLessThan(String value) {
			addCriterion("isbnNO <", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoLessThanOrEqualTo(String value) {
			addCriterion("isbnNO <=", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoLike(String value) {
			addCriterion("isbnNO like", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoNotLike(String value) {
			addCriterion("isbnNO not like", value, "isbnno");
			return this;
		}

		public Criteria andIsbnnoIn(List values) {
			addCriterion("isbnNO in", values, "isbnno");
			return this;
		}

		public Criteria andIsbnnoNotIn(List values) {
			addCriterion("isbnNO not in", values, "isbnno");
			return this;
		}

		public Criteria andIsbnnoBetween(String value1, String value2) {
			addCriterion("isbnNO between", value1, value2, "isbnno");
			return this;
		}

		public Criteria andIsbnnoNotBetween(String value1, String value2) {
			addCriterion("isbnNO not between", value1, value2, "isbnno");
			return this;
		}

		public Criteria andClassaIsNull() {
			addCriterion("classA is null");
			return this;
		}

		public Criteria andClassaIsNotNull() {
			addCriterion("classA is not null");
			return this;
		}

		public Criteria andClassaEqualTo(String value) {
			addCriterion("classA =", value, "classa");
			return this;
		}

		public Criteria andClassaNotEqualTo(String value) {
			addCriterion("classA <>", value, "classa");
			return this;
		}

		public Criteria andClassaGreaterThan(String value) {
			addCriterion("classA >", value, "classa");
			return this;
		}

		public Criteria andClassaGreaterThanOrEqualTo(String value) {
			addCriterion("classA >=", value, "classa");
			return this;
		}

		public Criteria andClassaLessThan(String value) {
			addCriterion("classA <", value, "classa");
			return this;
		}

		public Criteria andClassaLessThanOrEqualTo(String value) {
			addCriterion("classA <=", value, "classa");
			return this;
		}

		public Criteria andClassaLike(String value) {
			addCriterion("classA like", value, "classa");
			return this;
		}

		public Criteria andClassaNotLike(String value) {
			addCriterion("classA not like", value, "classa");
			return this;
		}

		public Criteria andClassaIn(List values) {
			addCriterion("classA in", values, "classa");
			return this;
		}

		public Criteria andClassaNotIn(List values) {
			addCriterion("classA not in", values, "classa");
			return this;
		}

		public Criteria andClassaBetween(String value1, String value2) {
			addCriterion("classA between", value1, value2, "classa");
			return this;
		}

		public Criteria andClassaNotBetween(String value1, String value2) {
			addCriterion("classA not between", value1, value2, "classa");
			return this;
		}

		public Criteria andProjectnoIsNull() {
			addCriterion("projectno is null");
			return this;
		}

		public Criteria andProjectnoIsNotNull() {
			addCriterion("projectno is not null");
			return this;
		}

		public Criteria andProjectnoEqualTo(String value) {
			addCriterion("projectno =", value, "projectno");
			return this;
		}

		public Criteria andProjectnoNotEqualTo(String value) {
			addCriterion("projectno <>", value, "projectno");
			return this;
		}

		public Criteria andProjectnoGreaterThan(String value) {
			addCriterion("projectno >", value, "projectno");
			return this;
		}

		public Criteria andProjectnoGreaterThanOrEqualTo(String value) {
			addCriterion("projectno >=", value, "projectno");
			return this;
		}

		public Criteria andProjectnoLessThan(String value) {
			addCriterion("projectno <", value, "projectno");
			return this;
		}

		public Criteria andProjectnoLessThanOrEqualTo(String value) {
			addCriterion("projectno <=", value, "projectno");
			return this;
		}

		public Criteria andProjectnoLike(String value) {
			addCriterion("projectno like", value, "projectno");
			return this;
		}

		public Criteria andProjectnoNotLike(String value) {
			addCriterion("projectno not like", value, "projectno");
			return this;
		}

		public Criteria andProjectnoIn(List values) {
			addCriterion("projectno in", values, "projectno");
			return this;
		}

		public Criteria andProjectnoNotIn(List values) {
			addCriterion("projectno not in", values, "projectno");
			return this;
		}

		public Criteria andProjectnoBetween(String value1, String value2) {
			addCriterion("projectno between", value1, value2, "projectno");
			return this;
		}

		public Criteria andProjectnoNotBetween(String value1, String value2) {
			addCriterion("projectno not between", value1, value2, "projectno");
			return this;
		}

		public Criteria andTotalwordIsNull() {
			addCriterion("totalWord is null");
			return this;
		}

		public Criteria andTotalwordIsNotNull() {
			addCriterion("totalWord is not null");
			return this;
		}

		public Criteria andTotalwordEqualTo(String value) {
			addCriterion("totalWord =", value, "totalword");
			return this;
		}

		public Criteria andTotalwordNotEqualTo(String value) {
			addCriterion("totalWord <>", value, "totalword");
			return this;
		}

		public Criteria andTotalwordGreaterThan(String value) {
			addCriterion("totalWord >", value, "totalword");
			return this;
		}

		public Criteria andTotalwordGreaterThanOrEqualTo(String value) {
			addCriterion("totalWord >=", value, "totalword");
			return this;
		}

		public Criteria andTotalwordLessThan(String value) {
			addCriterion("totalWord <", value, "totalword");
			return this;
		}

		public Criteria andTotalwordLessThanOrEqualTo(String value) {
			addCriterion("totalWord <=", value, "totalword");
			return this;
		}

		public Criteria andTotalwordLike(String value) {
			addCriterion("totalWord like", value, "totalword");
			return this;
		}

		public Criteria andTotalwordNotLike(String value) {
			addCriterion("totalWord not like", value, "totalword");
			return this;
		}

		public Criteria andTotalwordIn(List values) {
			addCriterion("totalWord in", values, "totalword");
			return this;
		}

		public Criteria andTotalwordNotIn(List values) {
			addCriterion("totalWord not in", values, "totalword");
			return this;
		}

		public Criteria andTotalwordBetween(String value1, String value2) {
			addCriterion("totalWord between", value1, value2, "totalword");
			return this;
		}

		public Criteria andTotalwordNotBetween(String value1, String value2) {
			addCriterion("totalWord not between", value1, value2, "totalword");
			return this;
		}

		public Criteria andWorkteacheridIsNull() {
			addCriterion("workTeacherId is null");
			return this;
		}

		public Criteria andWorkteacheridIsNotNull() {
			addCriterion("workTeacherId is not null");
			return this;
		}

		public Criteria andWorkteacheridEqualTo(Long value) {
			addCriterion("workTeacherId =", value, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridNotEqualTo(Long value) {
			addCriterion("workTeacherId <>", value, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridGreaterThan(Long value) {
			addCriterion("workTeacherId >", value, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridGreaterThanOrEqualTo(Long value) {
			addCriterion("workTeacherId >=", value, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridLessThan(Long value) {
			addCriterion("workTeacherId <", value, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridLessThanOrEqualTo(Long value) {
			addCriterion("workTeacherId <=", value, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridIn(List values) {
			addCriterion("workTeacherId in", values, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridNotIn(List values) {
			addCriterion("workTeacherId not in", values, "workteacherid");
			return this;
		}

		public Criteria andWorkteacheridBetween(Long value1, Long value2) {
			addCriterion("workTeacherId between", value1, value2,
					"workteacherid");
			return this;
		}

		public Criteria andWorkteacheridNotBetween(Long value1, Long value2) {
			addCriterion("workTeacherId not between", value1, value2,
					"workteacherid");
			return this;
		}

		public Criteria andWorkteachorresearchIsNull() {
			addCriterion("workTeachOrResearch is null");
			return this;
		}

		public Criteria andWorkteachorresearchIsNotNull() {
			addCriterion("workTeachOrResearch is not null");
			return this;
		}

		public Criteria andWorkteachorresearchEqualTo(String value) {
			addCriterion("workTeachOrResearch =", value, "workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchNotEqualTo(String value) {
			addCriterion("workTeachOrResearch <>", value, "workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchGreaterThan(String value) {
			addCriterion("workTeachOrResearch >", value, "workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchGreaterThanOrEqualTo(String value) {
			addCriterion("workTeachOrResearch >=", value, "workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchLessThan(String value) {
			addCriterion("workTeachOrResearch <", value, "workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchLessThanOrEqualTo(String value) {
			addCriterion("workTeachOrResearch <=", value, "workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchLike(String value) {
			addCriterion("workTeachOrResearch like", value,
					"workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchNotLike(String value) {
			addCriterion("workTeachOrResearch not like", value,
					"workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchIn(List values) {
			addCriterion("workTeachOrResearch in", values,
					"workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchNotIn(List values) {
			addCriterion("workTeachOrResearch not in", values,
					"workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchBetween(String value1,
				String value2) {
			addCriterion("workTeachOrResearch between", value1, value2,
					"workteachorresearch");
			return this;
		}

		public Criteria andWorkteachorresearchNotBetween(String value1,
				String value2) {
			addCriterion("workTeachOrResearch not between", value1, value2,
					"workteachorresearch");
			return this;
		}

		public Criteria andWorkteachernameIsNull() {
			addCriterion("workTeacherName is null");
			return this;
		}

		public Criteria andWorkteachernameIsNotNull() {
			addCriterion("workTeacherName is not null");
			return this;
		}

		public Criteria andWorkteachernameEqualTo(String value) {
			addCriterion("workTeacherName =", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameNotEqualTo(String value) {
			addCriterion("workTeacherName <>", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameGreaterThan(String value) {
			addCriterion("workTeacherName >", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameGreaterThanOrEqualTo(String value) {
			addCriterion("workTeacherName >=", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameLessThan(String value) {
			addCriterion("workTeacherName <", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameLessThanOrEqualTo(String value) {
			addCriterion("workTeacherName <=", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameLike(String value) {
			addCriterion("workTeacherName like", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameNotLike(String value) {
			addCriterion("workTeacherName not like", value, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameIn(List values) {
			addCriterion("workTeacherName in", values, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameNotIn(List values) {
			addCriterion("workTeacherName not in", values, "workteachername");
			return this;
		}

		public Criteria andWorkteachernameBetween(String value1, String value2) {
			addCriterion("workTeacherName between", value1, value2,
					"workteachername");
			return this;
		}

		public Criteria andWorkteachernameNotBetween(String value1,
				String value2) {
			addCriterion("workTeacherName not between", value1, value2,
					"workteachername");
			return this;
		}
	}
}