package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TAttmeeting;
import com.et59.cus.domain.entity.TAttmeetingExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAttmeetingDAOImpl extends SqlMapClientDaoSupport implements TAttmeetingDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public TAttmeetingDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int countByExample(TAttmeetingExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_attmeeting.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int deleteByExample(TAttmeetingExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_attmeeting.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int deleteByPrimaryKey(Long attendid) {
		TAttmeeting key = new TAttmeeting();
		key.setAttendid(attendid);
		int rows = getSqlMapClientTemplate().delete(
				"t_attmeeting.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void insert(TAttmeeting record) {
		getSqlMapClientTemplate().insert("t_attmeeting.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public void insertSelective(TAttmeeting record) {
		getSqlMapClientTemplate().insert(
				"t_attmeeting.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public List selectByExample(TAttmeetingExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_attmeeting.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public TAttmeeting selectByPrimaryKey(Long attendid) {
		TAttmeeting key = new TAttmeeting();
		key.setAttendid(attendid);
		TAttmeeting record = (TAttmeeting) getSqlMapClientTemplate()
				.queryForObject(
						"t_attmeeting.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int updateByExampleSelective(TAttmeeting record,
			TAttmeetingExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_attmeeting.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int updateByExample(TAttmeeting record, TAttmeetingExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_attmeeting.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int updateByPrimaryKeySelective(TAttmeeting record) {
		int rows = getSqlMapClientTemplate().update(
				"t_attmeeting.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	public int updateByPrimaryKey(TAttmeeting record) {
		int rows = getSqlMapClientTemplate().update(
				"t_attmeeting.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_attmeeting
	 * @ibatorgenerated  Fri Jul 17 10:42:38 CST 2015
	 */
	private static class UpdateByExampleParms extends TAttmeetingExample {
		private Object record;

		public UpdateByExampleParms(Object record, TAttmeetingExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}