package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TAtttrain;
import com.et59.cus.domain.entity.TAtttrainExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TAtttrainDAOImpl extends SqlMapClientDaoSupport implements TAtttrainDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public TAtttrainDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int countByExample(TAtttrainExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_atttrain.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int deleteByExample(TAtttrainExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_atttrain.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int deleteByPrimaryKey(Long atttrainid) {
		TAtttrain key = new TAtttrain();
		key.setAtttrainid(atttrainid);
		int rows = getSqlMapClientTemplate().delete(
				"t_atttrain.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public void insert(TAtttrain record) {
		getSqlMapClientTemplate().insert("t_atttrain.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public void insertSelective(TAtttrain record) {
		getSqlMapClientTemplate().insert(
				"t_atttrain.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public List selectByExample(TAtttrainExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_atttrain.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public TAtttrain selectByPrimaryKey(Long atttrainid) {
		TAtttrain key = new TAtttrain();
		key.setAtttrainid(atttrainid);
		TAtttrain record = (TAtttrain) getSqlMapClientTemplate()
				.queryForObject(
						"t_atttrain.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int updateByExampleSelective(TAtttrain record,
			TAtttrainExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_atttrain.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int updateByExample(TAtttrain record, TAtttrainExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_atttrain.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int updateByPrimaryKeySelective(TAtttrain record) {
		int rows = getSqlMapClientTemplate().update(
				"t_atttrain.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	public int updateByPrimaryKey(TAtttrain record) {
		int rows = getSqlMapClientTemplate().update(
				"t_atttrain.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_atttrain
	 * @ibatorgenerated  Fri Jul 17 17:56:36 CST 2015
	 */
	private static class UpdateByExampleParms extends TAtttrainExample {
		private Object record;

		public UpdateByExampleParms(Object record, TAtttrainExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}