package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TBookclub;
import com.et59.cus.domain.entity.TBookclubExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TBookclubDAOImpl extends SqlMapClientDaoSupport implements TBookclubDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public TBookclubDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int countByExample(TBookclubExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_bookclub.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int deleteByExample(TBookclubExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_bookclub.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int deleteByPrimaryKey(Long bookclubid) {
		TBookclub key = new TBookclub();
		key.setBookclubid(bookclubid);
		int rows = getSqlMapClientTemplate().delete(
				"t_bookclub.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void insert(TBookclub record) {
		getSqlMapClientTemplate().insert("t_bookclub.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public void insertSelective(TBookclub record) {
		getSqlMapClientTemplate().insert(
				"t_bookclub.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public List selectByExample(TBookclubExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_bookclub.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public TBookclub selectByPrimaryKey(Long bookclubid) {
		TBookclub key = new TBookclub();
		key.setBookclubid(bookclubid);
		TBookclub record = (TBookclub) getSqlMapClientTemplate()
				.queryForObject(
						"t_bookclub.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int updateByExampleSelective(TBookclub record,
			TBookclubExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_bookclub.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int updateByExample(TBookclub record, TBookclubExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_bookclub.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int updateByPrimaryKeySelective(TBookclub record) {
		int rows = getSqlMapClientTemplate().update(
				"t_bookclub.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	public int updateByPrimaryKey(TBookclub record) {
		int rows = getSqlMapClientTemplate().update(
				"t_bookclub.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_bookclub
	 * @ibatorgenerated  Wed Jul 22 17:12:28 CST 2015
	 */
	private static class UpdateByExampleParms extends TBookclubExample {
		private Object record;

		public UpdateByExampleParms(Object record, TBookclubExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}