package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TExchangeStu;
import com.et59.cus.domain.entity.TExchangeStuExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TExchangeStuDAOImpl extends SqlMapClientDaoSupport implements TExchangeStuDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public TExchangeStuDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int countByExample(TExchangeStuExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_exchange_stu.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int deleteByExample(TExchangeStuExample example) {
        int rows = getSqlMapClientTemplate().delete("t_exchange_stu.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int deleteByPrimaryKey(Long exchangestuid) {
        TExchangeStu key = new TExchangeStu();
        key.setExchangestuid(exchangestuid);
        int rows = getSqlMapClientTemplate().delete("t_exchange_stu.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void insert(TExchangeStu record) {
        getSqlMapClientTemplate().insert("t_exchange_stu.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void insertSelective(TExchangeStu record) {
        getSqlMapClientTemplate().insert("t_exchange_stu.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public List selectByExample(TExchangeStuExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_exchange_stu.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public TExchangeStu selectByPrimaryKey(Long exchangestuid) {
        TExchangeStu key = new TExchangeStu();
        key.setExchangestuid(exchangestuid);
        TExchangeStu record = (TExchangeStu) getSqlMapClientTemplate().queryForObject("t_exchange_stu.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByExampleSelective(TExchangeStu record, TExchangeStuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_exchange_stu.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByExample(TExchangeStu record, TExchangeStuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_exchange_stu.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByPrimaryKeySelective(TExchangeStu record) {
        int rows = getSqlMapClientTemplate().update("t_exchange_stu.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByPrimaryKey(TExchangeStu record) {
        int rows = getSqlMapClientTemplate().update("t_exchange_stu.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_exchange_stu
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private static class UpdateByExampleParms extends TExchangeStuExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExchangeStuExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}