package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TForeignExperts;
import com.et59.cus.domain.entity.TForeignExpertsExample;
import java.util.List;

public interface TForeignExpertsDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int countByExample(TForeignExpertsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int deleteByExample(TForeignExpertsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int deleteByPrimaryKey(Long foreignid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    void insert(TForeignExperts record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    void insertSelective(TForeignExperts record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    List selectByExample(TForeignExpertsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    TForeignExperts selectByPrimaryKey(Long foreignid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByExampleSelective(TForeignExperts record, TForeignExpertsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByExample(TForeignExperts record, TForeignExpertsExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByPrimaryKeySelective(TForeignExperts record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByPrimaryKey(TForeignExperts record);
}