package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TForeignExperts;
import com.et59.cus.domain.entity.TForeignExpertsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TForeignExpertsDAOImpl extends SqlMapClientDaoSupport implements TForeignExpertsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public TForeignExpertsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int countByExample(TForeignExpertsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_foreign_experts.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int deleteByExample(TForeignExpertsExample example) {
        int rows = getSqlMapClientTemplate().delete("t_foreign_experts.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int deleteByPrimaryKey(Long foreignid) {
        TForeignExperts key = new TForeignExperts();
        key.setForeignid(foreignid);
        int rows = getSqlMapClientTemplate().delete("t_foreign_experts.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void insert(TForeignExperts record) {
        getSqlMapClientTemplate().insert("t_foreign_experts.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void insertSelective(TForeignExperts record) {
        getSqlMapClientTemplate().insert("t_foreign_experts.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public List selectByExample(TForeignExpertsExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_foreign_experts.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public TForeignExperts selectByPrimaryKey(Long foreignid) {
        TForeignExperts key = new TForeignExperts();
        key.setForeignid(foreignid);
        TForeignExperts record = (TForeignExperts) getSqlMapClientTemplate().queryForObject("t_foreign_experts.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByExampleSelective(TForeignExperts record, TForeignExpertsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_foreign_experts.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByExample(TForeignExperts record, TForeignExpertsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_foreign_experts.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByPrimaryKeySelective(TForeignExperts record) {
        int rows = getSqlMapClientTemplate().update("t_foreign_experts.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByPrimaryKey(TForeignExperts record) {
        int rows = getSqlMapClientTemplate().update("t_foreign_experts.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_foreign_experts
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private static class UpdateByExampleParms extends TForeignExpertsExample {
        private Object record;

        public UpdateByExampleParms(Object record, TForeignExpertsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}