package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.THoldmeeting;
import com.et59.cus.domain.entity.THoldmeetingExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class THoldmeetingDAOImpl extends SqlMapClientDaoSupport implements THoldmeetingDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public THoldmeetingDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int countByExample(THoldmeetingExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_holdmeeting.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int deleteByExample(THoldmeetingExample example) {
        int rows = getSqlMapClientTemplate().delete("t_holdmeeting.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int deleteByPrimaryKey(Long holdid) {
        THoldmeeting key = new THoldmeeting();
        key.setHoldid(holdid);
        int rows = getSqlMapClientTemplate().delete("t_holdmeeting.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void insert(THoldmeeting record) {
        getSqlMapClientTemplate().insert("t_holdmeeting.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public void insertSelective(THoldmeeting record) {
        getSqlMapClientTemplate().insert("t_holdmeeting.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public List selectByExample(THoldmeetingExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_holdmeeting.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public THoldmeeting selectByPrimaryKey(Long holdid) {
        THoldmeeting key = new THoldmeeting();
        key.setHoldid(holdid);
        THoldmeeting record = (THoldmeeting) getSqlMapClientTemplate().queryForObject("t_holdmeeting.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByExampleSelective(THoldmeeting record, THoldmeetingExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_holdmeeting.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByExample(THoldmeeting record, THoldmeetingExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_holdmeeting.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByPrimaryKeySelective(THoldmeeting record) {
        int rows = getSqlMapClientTemplate().update("t_holdmeeting.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    public int updateByPrimaryKey(THoldmeeting record) {
        int rows = getSqlMapClientTemplate().update("t_holdmeeting.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    private static class UpdateByExampleParms extends THoldmeetingExample {
        private Object record;

        public UpdateByExampleParms(Object record, THoldmeetingExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}