package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.THoldmeeting;
import com.et59.cus.domain.entity.THoldmeetingExample;
import java.util.List;

public interface THoldmeetingDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int countByExample(THoldmeetingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int deleteByExample(THoldmeetingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int deleteByPrimaryKey(Long holdid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    void insert(THoldmeeting record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    void insertSelective(THoldmeeting record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    List selectByExample(THoldmeetingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    THoldmeeting selectByPrimaryKey(Long holdid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByExampleSelective(THoldmeeting record, THoldmeetingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByExample(THoldmeeting record, THoldmeetingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByPrimaryKeySelective(THoldmeeting record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_holdmeeting
     *
     * @ibatorgenerated Fri Jun 26 09:56:59 CST 2015
     */
    int updateByPrimaryKey(THoldmeeting record);
}