package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.THonorandother;
import com.et59.cus.domain.entity.THonorandotherExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class THonorandotherDAOImpl extends SqlMapClientDaoSupport implements THonorandotherDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public THonorandotherDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int countByExample(THonorandotherExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_honorandother.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int deleteByExample(THonorandotherExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_honorandother.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int deleteByPrimaryKey(Long honorid) {
		THonorandother key = new THonorandother();
		key.setHonorid(honorid);
		int rows = getSqlMapClientTemplate().delete(
				"t_honorandother.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public void insert(THonorandother record) {
		getSqlMapClientTemplate().insert(
				"t_honorandother.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public void insertSelective(THonorandother record) {
		getSqlMapClientTemplate().insert(
				"t_honorandother.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public List selectByExample(THonorandotherExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_honorandother.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public THonorandother selectByPrimaryKey(Long honorid) {
		THonorandother key = new THonorandother();
		key.setHonorid(honorid);
		THonorandother record = (THonorandother) getSqlMapClientTemplate()
				.queryForObject(
						"t_honorandother.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int updateByExampleSelective(THonorandother record,
			THonorandotherExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_honorandother.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int updateByExample(THonorandother record,
			THonorandotherExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_honorandother.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int updateByPrimaryKeySelective(THonorandother record) {
		int rows = getSqlMapClientTemplate().update(
				"t_honorandother.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	public int updateByPrimaryKey(THonorandother record) {
		int rows = getSqlMapClientTemplate().update(
				"t_honorandother.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_honorandother
	 * @ibatorgenerated  Sun Jul 05 16:04:06 CST 2015
	 */
	private static class UpdateByExampleParms extends THonorandotherExample {
		private Object record;

		public UpdateByExampleParms(Object record, THonorandotherExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}