package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.THonoraward;
import com.et59.cus.domain.entity.THonorawardExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class THonorawardDAOImpl extends SqlMapClientDaoSupport implements THonorawardDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public THonorawardDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int countByExample(THonorawardExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_honoraward.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int deleteByExample(THonorawardExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_honoraward.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int deleteByPrimaryKey(Long honorawardid) {
		THonoraward key = new THonoraward();
		key.setHonorawardid(honorawardid);
		int rows = getSqlMapClientTemplate().delete(
				"t_honoraward.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public void insert(THonoraward record) {
		getSqlMapClientTemplate().insert("t_honoraward.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public void insertSelective(THonoraward record) {
		getSqlMapClientTemplate().insert(
				"t_honoraward.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public List selectByExample(THonorawardExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_honoraward.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public THonoraward selectByPrimaryKey(Long honorawardid) {
		THonoraward key = new THonoraward();
		key.setHonorawardid(honorawardid);
		THonoraward record = (THonoraward) getSqlMapClientTemplate()
				.queryForObject(
						"t_honoraward.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int updateByExampleSelective(THonoraward record,
			THonorawardExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_honoraward.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int updateByExample(THonoraward record, THonorawardExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_honoraward.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int updateByPrimaryKeySelective(THonoraward record) {
		int rows = getSqlMapClientTemplate().update(
				"t_honoraward.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	public int updateByPrimaryKey(THonoraward record) {
		int rows = getSqlMapClientTemplate().update(
				"t_honoraward.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_honoraward
	 * @ibatorgenerated  Tue Jul 21 14:34:35 CST 2015
	 */
	private static class UpdateByExampleParms extends THonorawardExample {
		private Object record;

		public UpdateByExampleParms(Object record, THonorawardExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}