package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TLearnact;
import com.et59.cus.domain.entity.TLearnactExample;
import java.util.List;

public interface TLearnactDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int countByExample(TLearnactExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int deleteByExample(TLearnactExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int deleteByPrimaryKey(Long actid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    void insert(TLearnact record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    void insertSelective(TLearnact record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    List selectByExample(TLearnactExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    TLearnact selectByPrimaryKey(Long actid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByExampleSelective(TLearnact record, TLearnactExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByExample(TLearnact record, TLearnactExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByPrimaryKeySelective(TLearnact record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_learnact
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByPrimaryKey(TLearnact record);
}