package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TSocialevent;
import com.et59.cus.domain.entity.TSocialeventExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TSocialeventDAOImpl extends SqlMapClientDaoSupport implements TSocialeventDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public TSocialeventDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int countByExample(TSocialeventExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_socialevent.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int deleteByExample(TSocialeventExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_socialevent.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int deleteByPrimaryKey(Long eventid) {
		TSocialevent key = new TSocialevent();
		key.setEventid(eventid);
		int rows = getSqlMapClientTemplate().delete(
				"t_socialevent.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void insert(TSocialevent record) {
		getSqlMapClientTemplate().insert(
				"t_socialevent.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public void insertSelective(TSocialevent record) {
		getSqlMapClientTemplate().insert(
				"t_socialevent.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public List selectByExample(TSocialeventExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_socialevent.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public TSocialevent selectByPrimaryKey(Long eventid) {
		TSocialevent key = new TSocialevent();
		key.setEventid(eventid);
		TSocialevent record = (TSocialevent) getSqlMapClientTemplate()
				.queryForObject(
						"t_socialevent.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int updateByExampleSelective(TSocialevent record,
			TSocialeventExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_socialevent.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int updateByExample(TSocialevent record, TSocialeventExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_socialevent.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int updateByPrimaryKeySelective(TSocialevent record) {
		int rows = getSqlMapClientTemplate().update(
				"t_socialevent.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	public int updateByPrimaryKey(TSocialevent record) {
		int rows = getSqlMapClientTemplate().update(
				"t_socialevent.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_socialevent
	 * @ibatorgenerated  Sun Jul 26 13:46:16 CST 2015
	 */
	private static class UpdateByExampleParms extends TSocialeventExample {
		private Object record;

		public UpdateByExampleParms(Object record, TSocialeventExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}