package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TSocialevent;
import com.et59.cus.domain.entity.TSocialeventExample;
import java.util.List;

public interface TSocialeventDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int countByExample(TSocialeventExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int deleteByExample(TSocialeventExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int deleteByPrimaryKey(Long eventid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    void insert(TSocialevent record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    void insertSelective(TSocialevent record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    List selectByExample(TSocialeventExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    TSocialevent selectByPrimaryKey(Long eventid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByExampleSelective(TSocialevent record, TSocialeventExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByExample(TSocialevent record, TSocialeventExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByPrimaryKeySelective(TSocialevent record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_socialevent
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    int updateByPrimaryKey(TSocialevent record);
}