package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TStudentaward;
import com.et59.cus.domain.entity.TStudentawardExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TStudentawardDAOImpl extends SqlMapClientDaoSupport implements TStudentawardDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public TStudentawardDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int countByExample(TStudentawardExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_studentaward.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int deleteByExample(TStudentawardExample example) {
        int rows = getSqlMapClientTemplate().delete("t_studentaward.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int deleteByPrimaryKey(Long awardid) {
        TStudentaward key = new TStudentaward();
        key.setAwardid(awardid);
        int rows = getSqlMapClientTemplate().delete("t_studentaward.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void insert(TStudentaward record) {
        getSqlMapClientTemplate().insert("t_studentaward.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public void insertSelective(TStudentaward record) {
        getSqlMapClientTemplate().insert("t_studentaward.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public List selectByExample(TStudentawardExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_studentaward.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public TStudentaward selectByPrimaryKey(Long awardid) {
        TStudentaward key = new TStudentaward();
        key.setAwardid(awardid);
        TStudentaward record = (TStudentaward) getSqlMapClientTemplate().queryForObject("t_studentaward.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int updateByExampleSelective(TStudentaward record, TStudentawardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_studentaward.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int updateByExample(TStudentaward record, TStudentawardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_studentaward.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int updateByPrimaryKeySelective(TStudentaward record) {
        int rows = getSqlMapClientTemplate().update("t_studentaward.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    public int updateByPrimaryKey(TStudentaward record) {
        int rows = getSqlMapClientTemplate().update("t_studentaward.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_studentaward
     *
     * @ibatorgenerated Tue Jul 21 14:25:55 CST 2015
     */
    private static class UpdateByExampleParms extends TStudentawardExample {
        private Object record;

        public UpdateByExampleParms(Object record, TStudentawardExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}