package com.et59.cus.domain.dao;

import java.util.List;

import com.et59.cus.domain.entity.TTeacher;
import com.et59.cus.domain.entity.TTeacherExample;
import com.et59.cus.domain.entity.TTeacherWithBLOBs;

public interface TTeacherDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int countByExample(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int deleteByExample(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	void insert(TTeacherWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	void insertSelective(TTeacherWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	List selectByExampleWithBLOBs(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	List selectByExampleWithoutBLOBs(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	TTeacherWithBLOBs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int updateByExampleSelective(TTeacherWithBLOBs record,
			TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int updateByExample(TTeacherWithBLOBs record, TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int updateByExample(TTeacher record, TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int updateByPrimaryKeySelective(TTeacherWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int updateByPrimaryKey(TTeacherWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Thu Apr 09 13:51:52 CST 2015
	 */
	int updateByPrimaryKey(TTeacher record);

	/**
	 * 通过存储过程删除教师及相关表信息
	 * 
	 * @param id
	 */
	Integer deleteByProc(Long id);

	/**
	 * 新增并返回ID
	 */
	public Long insertSelectiveReturnId(TTeacherWithBLOBs record);
}