package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TTeacher;
import com.et59.cus.domain.entity.TTeacherExample;

import java.util.List;

public interface TTeacherDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int countByExample(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int deleteByExample(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	void insert(TTeacher record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	void insertSelective(TTeacher record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	List selectByExample(TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	TTeacher selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int updateByExampleSelective(TTeacher record, TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int updateByExample(TTeacher record, TTeacherExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int updateByPrimaryKeySelective(TTeacher record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_teacher
	 * @ibatorgenerated  Wed Mar 04 16:24:24 CST 2015
	 */
	int updateByPrimaryKey(TTeacher record);
	
	/**通过存储过程删除教师及相关表信息
	 * @param id
	 */
	public void deleteByProc(Long id);
}