package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TWork;
import com.et59.cus.domain.entity.TWorkExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TWorkDAOImpl extends SqlMapClientDaoSupport implements TWorkDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public TWorkDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int countByExample(TWorkExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_work.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int deleteByExample(TWorkExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_work.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int deleteByPrimaryKey(Long workid) {
		TWork key = new TWork();
		key.setWorkid(workid);
		int rows = getSqlMapClientTemplate().delete(
				"t_work.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public void insert(TWork record) {
		getSqlMapClientTemplate().insert("t_work.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public void insertSelective(TWork record) {
		getSqlMapClientTemplate().insert(
				"t_work.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public List selectByExample(TWorkExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_work.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public TWork selectByPrimaryKey(Long workid) {
		TWork key = new TWork();
		key.setWorkid(workid);
		TWork record = (TWork) getSqlMapClientTemplate().queryForObject(
				"t_work.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int updateByExampleSelective(TWork record, TWorkExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_work.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int updateByExample(TWork record, TWorkExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_work.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int updateByPrimaryKeySelective(TWork record) {
		int rows = getSqlMapClientTemplate().update(
				"t_work.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	public int updateByPrimaryKey(TWork record) {
		int rows = getSqlMapClientTemplate().update(
				"t_work.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_work
	 * @ibatorgenerated  Fri May 29 17:17:05 CST 2015
	 */
	private static class UpdateByExampleParms extends TWorkExample {
		private Object record;

		public UpdateByExampleParms(Object record, TWorkExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}